part of localized;

const _enemy = LocalizedGroup([
  LocalizedText(chs: '影从者', jpn: 'シャドウサーヴァント', eng: 'Shadow Servant'),
  LocalizedText(chs: '亡者之门', jpn: '', eng: 'Door of the Undead'),
  LocalizedText(chs: '勇者之门', jpn: '', eng: 'Door of Brave'),
  LocalizedText(chs: '圣者之门', jpn: '', eng: 'Door of Saint'),
  LocalizedText(chs: '霸者之门', jpn: '', eng: 'Door of Champion'),
  LocalizedText(chs: '黎明之手', jpn: '', eng: 'Hand of Dawn'),
  LocalizedText(chs: '黎明之腕', jpn: '', eng: 'Arm of Dawn'),
  LocalizedText(chs: '黎明之刚腕', jpn: '', eng: 'Strong Arm of Dawn'),
  LocalizedText(chs: '黎明之神腕', jpn: '', eng: 'Divine Arm of Dawn'),
  LocalizedText(chs: '黎明之炎腕', jpn: '', eng: 'Radiant Arm of Dawn'),
  LocalizedText(chs: '圣诞之手', jpn: '', eng: 'Christmas Hand'),
  LocalizedText(chs: '圣诞手套', jpn: '', eng: 'Christmas Glove'),
  LocalizedText(chs: '圣诞之拳', jpn: '', eng: 'Christmas Fist'),
  LocalizedText(chs: '驱鬼之手', jpn: '', eng: ''),
  LocalizedText(chs: '骷髅兵', jpn: '', eng: 'Skeleton'),
  LocalizedText(chs: '南瓜骷髅兵', jpn: '', eng: 'Pumpkin Skeleton'),
  LocalizedText(chs: '骸骨之王', jpn: '', eng: 'Skeleton King'),
  LocalizedText(chs: '金属南瓜骷髅兵', jpn: '', eng: 'Metal Pumpkin Skeleton'),
  LocalizedText(chs: '龙牙兵', jpn: '', eng: 'Dragon Tooth Warrior'),
  LocalizedText(chs: '古代兵', jpn: '', eng: 'Ancient Soldier'),
  LocalizedText(chs: '古代兵僵尸', jpn: '', eng: 'Ancient Zombie'),
  LocalizedText(chs: '联合罗马士兵', jpn: '', eng: 'Roman Soldier'),
  LocalizedText(chs: '罗马士兵', jpn: '', eng: 'Roman Soldier'),
  LocalizedText(chs: '中世兵', jpn: '', eng: 'Medieval Soldier'),
  LocalizedText(chs: '中世兵僵尸', jpn: '', eng: 'Medieval Zombie'),
  LocalizedText(chs: '法国士兵', jpn: '', eng: 'French Soldier'),
  LocalizedText(chs: '近代兵', jpn: '', eng: 'Pre-Modern Soldier'),
  LocalizedText(chs: '近代兵僵尸', jpn: '', eng: 'Pre-Modern Zombie'),
  LocalizedText(chs: '海盗', jpn: '', eng: 'Pirate'),
  LocalizedText(chs: '从者庆典参加者', jpn: '', eng: 'Serva Fes Attendee'),
  LocalizedText(chs: '僵尸', jpn: '', eng: 'Zombie'),
  LocalizedText(chs: '海盗僵尸', jpn: '', eng: 'Pirate Zombie'),
  LocalizedText(chs: '鬼魂', jpn: '', eng: 'Ghost'),
  LocalizedText(chs: '恐怖鬼魂', jpn: '', eng: 'Terror Ghost'),
  LocalizedText(chs: '古代鬼魂', jpn: '', eng: 'Ancient Ghost'),
  LocalizedText(chs: '稻草人', jpn: '', eng: 'Scarecrow'),
  LocalizedText(chs: '忌灵', jpn: '', eng: 'Abhor Soul'),
  LocalizedText(chs: '金属稻草人', jpn: '', eng: 'Metal Scarecrow'),
  LocalizedText(chs: '派对鬼魂', jpn: '', eng: 'Gallû Spirit'),
  LocalizedText(chs: '假面鬼魂', jpn: '', eng: 'Mask Ghost'),
  LocalizedText(chs: '蒸汽鬼魂', jpn: '', eng: 'Steam Ghost'),
  LocalizedText(chs: '恶魔', jpn: '', eng: 'Demon'),
  LocalizedText(chs: '上级恶魔', jpn: '', eng: 'Greater Demon'),
  LocalizedText(chs: '高等恶魔', jpn: '', eng: 'Archdemon'),
  LocalizedText(chs: '自动人偶', jpn: '', eng: 'Automata'),
  LocalizedText(chs: '杀戮人偶', jpn: '', eng: 'Killing Doll'),
  LocalizedText(chs: '陈旧装置', jpn: '', eng: 'Old Gear'),
  LocalizedText(chs: '花腔歌手', jpn: '', eng: 'Coloratuna'),
  LocalizedText(chs: '克里斯蒂娜', jpn: '', eng: 'Christine'),
  LocalizedText(chs: '傀儡兵', jpn: '', eng: 'Terracotta Warrior'),
  LocalizedText(chs: '古董自动人偶', jpn: '', eng: 'Antique Automata'),
  LocalizedText(chs: '假面自动人偶', jpn: '', eng: 'Mask Automata'),
  LocalizedText(
      chs: '对人歼灭装置', jpn: '', eng: 'Anti-Personnel Annihilation Device'),
  LocalizedText(chs: '魔偶', jpn: '', eng: 'Golem'),
  LocalizedText(chs: '石魔偶', jpn: '', eng: 'Stone Golem'),
  LocalizedText(chs: '金属魔偶', jpn: '', eng: 'Iron Golem'),
  LocalizedText(chs: '水晶魔偶', jpn: '', eng: 'Crystal Golem'),
  LocalizedText(chs: '红宝石魔偶', jpn: '', eng: 'Ruby Golem'),
  LocalizedText(chs: '双子钢铁魔偶', jpn: '', eng: 'Twin Steel Golem'),
  LocalizedText(chs: '雪人', jpn: '', eng: 'Snowman'),
  LocalizedText(chs: '巨型雪人', jpn: '', eng: 'Giant Snowman'),
  LocalizedText(chs: '饼干魔偶', jpn: '', eng: 'Biscuit Golem'),
  LocalizedText(chs: '阿维斯布隆魔偶', jpn: '', eng: 'Golem'),
  LocalizedText(chs: '双足飞龙', jpn: '', eng: 'Wyvern'),
  LocalizedText(chs: '恐惧飞龙', jpn: '', eng: 'Wyvern Dread'),
  LocalizedText(chs: '恶魔飞龙', jpn: '', eng: 'Wyvern Evil'),
  LocalizedText(chs: '古代飞龙', jpn: '', eng: 'Wyvern Classic'),
  LocalizedText(chs: '原始双足飞龙', jpn: '', eng: 'Wyvern Origin'),
  LocalizedText(chs: '彩虹双足飞龙', jpn: '', eng: 'Rainbow Wyvern'),
  LocalizedText(chs: '风暴双足飞龙', jpn: '', eng: 'Wyvern Tempest'),
  LocalizedText(chs: '龙', jpn: '', eng: 'Dragon'),
  LocalizedText(chs: '巨龙', jpn: '', eng: 'Great Dragon'),
  LocalizedText(chs: '长老龙', jpn: '', eng: 'Primeval Dragon'),
  LocalizedText(chs: '太古龙', jpn: '', eng: 'Elder Dragon'),
  LocalizedText(chs: '法夫纳', jpn: '', eng: 'Fafnir'),
  LocalizedText(chs: '巴修穆', jpn: '', eng: 'Bašmu'),
  LocalizedText(chs: '黄金龙', jpn: '', eng: 'Golden Dragon'),
  LocalizedText(chs: '亚马逊人', jpn: '', eng: 'Amazoness'),
  LocalizedText(chs: '亚马逊队长', jpn: '', eng: 'Amazoness Leader'),
  LocalizedText(chs: '亚马逊女王', jpn: '', eng: 'Amazoness Queen'),
  LocalizedText(chs: '蛇女', jpn: '', eng: 'Lamia'),
  LocalizedText(chs: '那伽', jpn: '', eng: 'Naga'),
  LocalizedText(chs: '那伽王', jpn: '', eng: 'Naga Raja'),
  LocalizedText(chs: '蛇女女王', jpn: '', eng: 'Lamia Queen'),
  LocalizedText(chs: '原始蛇女', jpn: '', eng: 'Origin Lamia'),
  LocalizedText(chs: '半人马', jpn: '', eng: 'Centaur'),
  LocalizedText(chs: '半人马骑士', jpn: '', eng: 'Centaur Knight'),
  LocalizedText(chs: '半人马圣骑', jpn: '', eng: 'Centaur Paladin'),
  LocalizedText(chs: '奇美拉', jpn: '', eng: 'Chimera'),
  LocalizedText(chs: '白色奇美拉', jpn: '', eng: 'White Chimera'),
  LocalizedText(chs: '超级奇美拉', jpn: '', eng: 'Super Chimera'),
  LocalizedText(chs: '达温', jpn: '', eng: 'Gdon'),
  LocalizedText(chs: '原始奇美拉', jpn: '', eng: 'Origin Chimera'),
  LocalizedText(chs: '咒语书', jpn: '', eng: 'Spellbook'),
  LocalizedText(chs: '雷电咒书', jpn: '', eng: 'Thunder Book'),
  LocalizedText(chs: '火焰咒书', jpn: '', eng: 'Fire Book'),
  LocalizedText(chs: '疾风咒书', jpn: '', eng: 'Wind Bood'),
  LocalizedText(chs: '冰雪咒书', jpn: '', eng: 'Ice Book'),
  LocalizedText(chs: '魔导书', jpn: '', eng: 'Grimoire'),
  LocalizedText(chs: '大魔道书', jpn: '', eng: 'Greater Grimoire'),
  LocalizedText(chs: '咒本', jpn: '', eng: 'Japanese Anthology Book'),
  LocalizedText(chs: '最初的咒本', jpn: '', eng: 'Primeval Accursed Book'),
  LocalizedText(chs: '人工生命体', jpn: '', eng: 'Homunculus'),
  LocalizedText(chs: '人工生命体原型', jpn: '', eng: 'Proto Homunculus'),
  LocalizedText(chs: '狼人', jpn: '', eng: 'Werewolf'),
  LocalizedText(chs: '豹人', jpn: '', eng: 'Werejaguar'),
  LocalizedText(chs: '哥布林', jpn: '', eng: 'Goblin'),
  LocalizedText(chs: '驯鹿人', jpn: '', eng: 'Reindeer Man'),
  LocalizedText(chs: '巨型驯鹿人', jpn: '', eng: 'Great Reindeer Man'),
  LocalizedText(chs: '超级驯鹿人', jpn: '', eng: 'Super Reindeer Man'),
  LocalizedText(chs: '混沌机械兵', jpn: '', eng: 'Helter Skelter'),
  LocalizedText(chs: '南瓜无人机', jpn: '', eng: 'Pumpkin Drone'),
  LocalizedText(chs: '西装尸人', jpn: '', eng: 'Business Suit Undead'),
  LocalizedText(chs: '背心尸人', jpn: '', eng: 'Tank top Undead'),
  LocalizedText(chs: 'DeadMan', jpn: '', eng: 'DeadMan'),
  LocalizedText(chs: '七人御佐姬', jpn: '', eng: 'Vengeful Spirit of Seven People'),
  LocalizedText(chs: '长发公主', jpn: '', eng: 'Rapunzel'),
  LocalizedText(chs: '大无间地狱堂', jpn: '', eng: 'Massive Ghost'),
  LocalizedText(chs: '不净观太极殿', jpn: '', eng: 'Massive Ghost'),
  LocalizedText(chs: '通晓恩怨的魂之集群', jpn: '', eng: 'Massive Ghost'),
  LocalizedText(chs: '烟醉哈桑', jpn: '', eng: 'Massive Ghost'),
  LocalizedText(chs: '鸣钟之物', jpn: '', eng: 'Massive Ghost'),
  LocalizedText(chs: '巨大鬼魂', jpn: '', eng: 'Massive Ghost'),
  LocalizedText(chs: '罗密欧与朱丽叶', jpn: '', eng: 'Romeo and Juliet'),
  LocalizedText(chs: '谜题', jpn: '', eng: 'Enigma'),
  LocalizedText(chs: '边狱大灵', jpn: '', eng: 'Limbo'),
  LocalizedText(chs: '女官鬼魂', jpn: '', eng: 'Lynchpin Maid'),
  LocalizedText(chs: '巨大蒸汽鬼魂', jpn: '', eng: 'Massive Stram Ghost'),
  LocalizedText(chs: '徐福', jpn: '', eng: 'Xu Fu'),
  LocalizedText(chs: '守护者', jpn: '', eng: 'Spriggan'),
  LocalizedText(chs: '青铜守护者', jpn: '', eng: 'Bronze Spriggan'),
  LocalizedText(chs: '李尔王', jpn: '', eng: 'King Lear'),
  LocalizedText(chs: '双角兽', jpn: '', eng: 'Bicorn'),
  LocalizedText(chs: '双角兽之王', jpn: '', eng: 'Emperorcorn'),
  LocalizedText(chs: '神马高耳', jpn: '', eng: 'Uchchaihshravas'),
  LocalizedText(chs: '凝视者', jpn: '', eng: 'Gazer'),
  LocalizedText(chs: '观察机', jpn: '', eng: 'Spotter'),
  LocalizedText(chs: '南瓜凝视者', jpn: '', eng: 'Pumpkin Gazer'),
  LocalizedText(chs: '噬魂者', jpn: '', eng: 'Soul Eater'),
  LocalizedText(chs: '星之兽', jpn: '', eng: 'Astral Critter'),
  LocalizedText(chs: '乌修穆迦尔', jpn: '', eng: 'Ušumgallu'),
  LocalizedText(chs: '萨罗摩', jpn: '', eng: 'Sarama'),
  LocalizedText(chs: '机械化步兵', jpn: '', eng: 'Mechanized Infantry'),
  LocalizedText(chs: '凯尔特士兵', jpn: '', eng: 'Celtic Soldier'),
  LocalizedText(chs: '德鲁伊', jpn: '', eng: 'Druid'),
  LocalizedText(chs: '看守', jpn: '', eng: 'Warden'),
  LocalizedText(chs: '小魔', jpn: '', eng: 'Little Demon'),
  LocalizedText(chs: '海魔', jpn: '', eng: 'Sea Demon'),
  LocalizedText(chs: '大食海魔', jpn: '', eng: 'Gluttonous Sea Demon'),
  LocalizedText(chs: '穆修玛夫', jpn: '', eng: 'Mušmaḫḫū'),
  LocalizedText(chs: '翅刃虫', jpn: '', eng: 'Bladed-Wing Insect'),
  LocalizedText(chs: '翅刃群虫', jpn: '', eng: 'Bladed-Wing Swarm'),
  LocalizedText(chs: '迅速之马库尔', jpn: '', eng: 'Makuru the Quick'),
  LocalizedText(chs: '基底之扎伊德', jpn: '', eng: 'Zayd the Base'),
  LocalizedText(chs: '怪腕之戈兹尔', jpn: '', eng: 'Remarkable Gozuru'),
  LocalizedText(chs: '醉酒城里人', jpn: '', eng: 'Drunken Citizen'),
  LocalizedText(chs: '农村亭卒', jpn: '', eng: 'Agricultural Resident Employee'),
  LocalizedText(chs: '鬼之左腕', jpn: '', eng: 'Demon Arm'),
  LocalizedText(chs: '鬼之右腕', jpn: '', eng: 'Demon Arm'),
  LocalizedText(chs: '苍雷石', jpn: '', eng: 'Thunder Stone'),
  LocalizedText(chs: '碧雷石', jpn: '', eng: 'Thunder Stone'),
  LocalizedText(chs: '技喰丸', jpn: '', eng: 'Wazahamimaru'),
  LocalizedText(chs: '风越丸', jpn: '', eng: 'Kazekoemaru'),
  LocalizedText(chs: '轰力丸', jpn: '', eng: 'Gōrikimaru'),
  LocalizedText(chs: '小鬼', jpn: '', eng: 'Oni lmp'),
  LocalizedText(chs: '邪鬼', jpn: '', eng: 'Oni Devil'),
  LocalizedText(chs: '祟鬼', jpn: '', eng: 'Cursed Oni'),
  LocalizedText(chs: '南瓜食人鬼·J', jpn: '', eng: 'Pumpkin Ogre・J'),
  LocalizedText(chs: '赤南瓜WAN', jpn: '', eng: 'Red Pumpkin MARU'),
  LocalizedText(chs: '绿南瓜WAN', jpn: '', eng: 'Green Pumpkin MARU'),
  LocalizedText(chs: '青南瓜WAN', jpn: '', eng: 'Blue Pumpkin MARU'),
  LocalizedText(chs: '鬼王朱裸', jpn: '', eng: 'Oni King Shura'),
  LocalizedText(chs: '虎熊童子', jpn: '', eng: 'Torakuma Dōji'),
  LocalizedText(chs: '大翁鬼', jpn: '', eng: 'Hakushikijyo'),
  LocalizedText(chs: '失心之人', jpn: '', eng: 'Soulless One'),
  LocalizedText(chs: '失心罪人', jpn: '', eng: 'Soulless Sinner'),
  LocalizedText(chs: '亡者', jpn: '', eng: 'Deceased One'),
  LocalizedText(chs: '杀人鬼', jpn: '', eng: 'Cutthroat'),
  LocalizedText(chs: '肃正骑士', jpn: '', eng: 'Knight Enforcer'),
  LocalizedText(chs: '南瓜骑士', jpn: '', eng: 'Pumpkin Knight'),
  LocalizedText(chs: '金属南瓜骑士', jpn: '', eng: 'Metal Pumpkin Knight'),
  LocalizedText(chs: '自动防卫装置', jpn: '', eng: 'Automated Defense Unit'),
  LocalizedText(chs: '自动防卫装置·二式', jpn: '', eng: 'Automated Defense Unit Mk-2'),
  LocalizedText(chs: '舞动的硬币', jpn: '', eng: 'Dancing Coin'),
  LocalizedText(chs: '斯芬克斯', jpn: '', eng: 'Sphinx'),
  LocalizedText(chs: '女王斯芬克斯', jpn: '', eng: 'Sphinx Queen'),
  LocalizedText(chs: '卡夫拉斯芬克斯', jpn: '', eng: 'Khafre Sphinx'),
  LocalizedText(chs: '伊夫利塔', jpn: '', eng: 'Efreet'),
  LocalizedText(chs: '花之邪神', jpn: '', eng: 'Evil God of the Flower'),
  LocalizedText(chs: '大寄居蟹', jpn: '', eng: 'Giant Hermit Crab'),
  LocalizedText(chs: '毒寄居蟹', jpn: '', eng: 'Poisonous Hermit Crab'),
  LocalizedText(chs: '千年寄居蟹', jpn: '', eng: 'Millennium Hermit Crab'),
  LocalizedText(chs: '破坏兽', jpn: '', eng: 'Razrushat'),
  LocalizedText(chs: '魔猪', jpn: '', eng: 'Demon Boar'),
  LocalizedText(chs: '秽猪', jpn: '', eng: 'Demon Boar'),
  LocalizedText(chs: '巨大魔猪', jpn: '', eng: 'Calydonian Boar'),
  LocalizedText(chs: '机械魔猪', jpn: '', eng: 'Mecha Demon Boar'),
  LocalizedText(chs: '迷你小库', jpn: '', eng: 'Mini Cú-chan'),
  LocalizedText(chs: '魔法杖', jpn: '', eng: 'Magical Stick'),
  LocalizedText(chs: '魔法杖！', jpn: '', eng: 'Magical Stick!'),
  LocalizedText(chs: '魔法杖～', jpn: '', eng: 'Magical Stick~'),
  LocalizedText(chs: '魔法杖？', jpn: '', eng: 'Magical Stick?'),
  LocalizedText(chs: '乌利迪姆', jpn: '', eng: 'Uridimmu'),
  LocalizedText(chs: '冰雪之狼', jpn: '', eng: 'Íss Úlfr'),
  LocalizedText(chs: '乌伽尔', jpn: '', eng: 'Ugallu'),
  LocalizedText(chs: '蝎狮', jpn: '', eng: 'Manticore'),
  LocalizedText(chs: '冰雪加姆', jpn: '', eng: 'Íss Garmr'),
  LocalizedText(chs: '穆修胡休', jpn: '', eng: 'Mušḫuššu'),
  LocalizedText(chs: '巴西利斯克', jpn: '', eng: 'Basilisk'),
  LocalizedText(chs: '咆哮兽', jpn: '', eng: 'Krichat\''),
  LocalizedText(chs: '仿科摩多巨蜥', jpn: '', eng: 'Pseudo-Komodo Dragon'),
  LocalizedText(
      chs: '复合神性戈耳工', jpn: '複合神性ゴルゴーン', eng: 'Composite Deity Gorgon'),
  LocalizedText(chs: '拉赫穆', jpn: '', eng: 'Laḫmu'),
  LocalizedText(chs: '巴力拉赫穆', jpn: '', eng: 'Bel Laḫmu'),
  LocalizedText(chs: '魔性之女', jpn: '', eng: 'Tiamat'),
  LocalizedText(chs: '小混混', jpn: '', eng: 'Hoodlum'),
  LocalizedText(chs: '流氓', jpn: '', eng: 'Yakuza'),
  LocalizedText(chs: '雀蜂', jpn: '', eng: 'Hornet'),
  LocalizedText(chs: '雀蜂1', jpn: '', eng: 'Hornet1'),
  LocalizedText(chs: '雀蜂2', jpn: '', eng: 'Hornet2'),
  LocalizedText(chs: '酷吏', jpn: '', eng: 'Atrocious Officer'),
  LocalizedText(chs: '女海盗', jpn: '', eng: 'Female Pirate'),
  LocalizedText(chs: '许德拉', jpn: '', eng: 'Hydra'),
  LocalizedText(chs: '大蛇', jpn: '', eng: 'Orochi'),
  LocalizedText(chs: '恶魔御座', jpn: '', eng: 'D\'yavol Tron'),
  LocalizedText(chs: '原始许德拉', jpn: '', eng: 'Origin Hydra'),
  LocalizedText(chs: '古伽兰那', jpn: '', eng: 'Gugalanna'),
  LocalizedText(chs: '黑武者', jpn: '', eng: 'Black Samurai'),
  LocalizedText(chs: '南瓜骑士·J', jpn: '', eng: 'Pumpkin Knight・J'),
  LocalizedText(chs: '暗之新选组队士', jpn: '', eng: 'Dark Shinsengumi Troop'),
  LocalizedText(chs: '量产型机械伊丽亲', jpn: '', eng: 'Mass-Produced Mecha Eli-chan'),
  LocalizedText(chs: '食尸鬼', jpn: '', eng: 'Ghoul'),
  LocalizedText(chs: '食尸鬼·嫉妒', jpn: '', eng: 'Ghoul Prophet'),
  LocalizedText(chs: '食尸鬼·暴食', jpn: '', eng: 'Ghoul Glutton'),
  LocalizedText(chs: '元老食尸鬼', jpn: '', eng: 'Elder Ghoul'),
  LocalizedText(chs: '灰狼', jpn: '', eng: 'Grey Wolf'),
  LocalizedText(chs: '夏塔克鸟', jpn: '', eng: 'Shantak'),
  LocalizedText(chs: '迦楼罗', jpn: '', eng: 'Garuda'),
  LocalizedText(chs: '杀戮猎兵', jpn: '', eng: 'Oprichnik'),
  LocalizedText(chs: '亚种空想树的种子', jpn: '', eng: 'Quixotic Tree Seed'),
  LocalizedText(chs: '雅嘎', jpn: '', eng: 'Yaga'),
  LocalizedText(chs: '英灵兵', jpn: '', eng: 'Heavy Armoured Warrior'),
  LocalizedText(chs: '魔导僧兵', jpn: '', eng: 'Heretical Warrior Monk'),
  LocalizedText(chs: '黑巨人', jpn: '', eng: 'Black Giant'),
  LocalizedText(chs: '霜之巨人', jpn: '', eng: 'Hrimthurse'),
  LocalizedText(chs: '山之巨人', jpn: '', eng: 'Bergrisi'),
  LocalizedText(chs: '火之巨人', jpn: '', eng: 'Múspell'),
  LocalizedText(chs: '苏鲁特', jpn: '', eng: 'Surtr'),
  LocalizedText(chs: '苏鲁特·芬里厄', jpn: '', eng: 'Surtr・Fenrir'),
  LocalizedText(chs: '瓦尔基里', jpn: '', eng: 'Walküre'),
  LocalizedText(chs: '斩首鸡', jpn: '', eng: 'Bhopal Chicken'),
  LocalizedText(chs: '斩首鸡王', jpn: '', eng: 'King Vorpal Chicken'),
  LocalizedText(chs: '禁卫兵', jpn: '', eng: 'Royal Guard'),
  LocalizedText(chs: '多多益善号', jpn: '', eng: 'The More The Merrier'),
  LocalizedText(chs: '鵺', jpn: '', eng: 'Nue'),
  LocalizedText(chs: '秽神', jpn: '', eng: 'Corrupted God'),
  LocalizedText(chs: '魔猿', jpn: '', eng: 'Demonic Monkey'),
  LocalizedText(chs: '温泉魔猿', jpn: '', eng: 'Demonic Monkey'),
  LocalizedText(chs: '新年魔猿', jpn: '', eng: 'Demonic Monkey'),
  LocalizedText(chs: '包袱布魔猿', jpn: '', eng: 'Demonic Monkey'),
  LocalizedText(chs: '女官', jpn: '', eng: 'Ōoku Jochū'),
  LocalizedText(chs: '上级女官', jpn: '', eng: 'Senior Jochū'),
  LocalizedText(chs: '庄严的石像', jpn: '', eng: 'Statue of Gratitude'),
  LocalizedText(chs: '迦利', jpn: '', eng: 'Kali'),
  LocalizedText(chs: '迦利·集合体', jpn: '', eng: 'Kali Sangha'),
  LocalizedText(chs: '伟大那伽', jpn: '', eng: 'Mahānaga'),
  LocalizedText(chs: '亚特兰蒂斯防卫兵', jpn: '', eng: 'Atlantean Defense Troop'),
  LocalizedText(chs: '原型', jpn: '', eng: 'Prototype'),
  LocalizedText(chs: '刻耳柏洛斯', jpn: '', eng: 'Cerberus'),
  LocalizedText(chs: '广域歼灭兵器', jpn: '', eng: 'Wide-Area Annihilation Ordnance'),
  LocalizedText(chs: '奥林波斯士兵', jpn: '', eng: 'Olympian Soldier'),
  LocalizedText(chs: '女佣娃娃', jpn: '', eng: 'Helper Doll'),
  LocalizedText(chs: '土蜘蛛', jpn: '', eng: 'Tsuchigumo'),
  LocalizedText(chs: '大土蜘蛛·玖贺耳之御笠', jpn: '', eng: 'Great Tsuchigumo'),
  // 2.6
  LocalizedText(chs: '死神', jpn: '', eng: 'Mors'),
  LocalizedText(chs: '大型死神', jpn: '', eng: 'Large Mors'),
  LocalizedText(chs: '森の獣', jpn: '森の獣', eng: 'Forest Beast'),
  LocalizedText(chs: '牙之氏族', jpn: '', eng: 'Fang Clan'),
  LocalizedText(chs: '眼镜蛇', jpn: 'ブジャンガ', eng: "Bhujanga"),
  // LocalizedText(chs: '', jpn: 'よどみ', eng: ''),
  LocalizedText(chs: '黑犬', jpn: '', eng: 'Black Dog'),
  LocalizedText(chs: '摩根士兵', jpn: '', eng: "Queen's Soldier"),
  LocalizedText(chs: '死神人类', jpn: '', eng: 'Human-Mors'),
  LocalizedText(chs: '王之氏族', jpn: '', eng: 'Royal Clan'),
  LocalizedText(chs: '王之氏族·小兵', jpn: '', eng: 'Royal Clan・Veteran'),
  LocalizedText(chs: '王之氏族·士官', jpn: '', eng: 'Royal Clan・Cygan'),

  // category
  LocalizedText(chs: '门', jpn: '', eng: 'Door'),
  LocalizedText(chs: '手', jpn: '', eng: 'Hand/Arm'),
  LocalizedText(chs: '骷髅兵', jpn: '', eng: 'Skeleton'),
  LocalizedText(chs: '龙牙兵', jpn: '', eng: 'Dragon Tooth Warrior'),
  LocalizedText(chs: '士兵', jpn: '', eng: 'Soldier'),
  LocalizedText(chs: '僵尸', jpn: '', eng: 'Zombie'),
  LocalizedText(chs: '鬼魂', jpn: '', eng: 'Ghost'),
  LocalizedText(chs: '恶魔', jpn: '', eng: 'Demon'),
  LocalizedText(chs: '自动人偶', jpn: '', eng: 'Automata'),
  LocalizedText(chs: '魔偶', jpn: '', eng: 'Golem'),
  LocalizedText(chs: '双足飞龙', jpn: '', eng: 'Wyvern'),
  LocalizedText(chs: '龙·巴修穆', jpn: '', eng: 'Dragon/Basmu'),
  LocalizedText(chs: '亚马逊人', jpn: '', eng: 'Amazoness'),
  LocalizedText(chs: '蛇女', jpn: '', eng: 'Lamia/Naga'),
  LocalizedText(chs: '半人马', jpn: '', eng: 'Centaur'),
  LocalizedText(chs: '奇美拉', jpn: '', eng: 'Chimera'),
  LocalizedText(chs: '咒语书', jpn: '', eng: 'Book'),
  LocalizedText(chs: '人工生命体', jpn: '', eng: 'Homunculus'),
  LocalizedText(chs: '兽人', jpn: '', eng: 'Beastman'),
  LocalizedText(chs: '混沌机械兵', jpn: '', eng: 'Helter Skelter'),
  LocalizedText(chs: '尸人', jpn: '', eng: 'Deadman/Undead'),
  // LocalizedText(chs: '七人御佐姬', jpn: '', eng: ''),
  LocalizedText(chs: '巨大首领鬼魂', jpn: '', eng: 'Massive Ghost'),
  LocalizedText(chs: '守护者', jpn: '', eng: 'Spriggan'),
  LocalizedText(chs: '双角兽', jpn: '', eng: 'Bicorn'),
  LocalizedText(chs: '凝视者', jpn: '', eng: 'Gazer'),
  LocalizedText(chs: '噬魂者·乌修穆迦尔', jpn: '', eng: 'Soul Eater/Usumgallu'),
  LocalizedText(chs: '机械化步兵', jpn: '', eng: 'Mechanized Infantry'),
  LocalizedText(chs: '凯尔特士兵', jpn: '', eng: 'Celtic Soldier'),
  LocalizedText(chs: '海魔·穆修玛夫', jpn: '', eng: 'Little Demon/Musmahhu'),
  LocalizedText(chs: '翅刃虫', jpn: '', eng: 'Bladed-Wing Insect'),
  LocalizedText(chs: '哈桑', jpn: '', eng: 'Hassan'),
  LocalizedText(chs: '醉酒城里人·农村亭卒', jpn: '', eng: 'Drunken Citizen'),
  LocalizedText(chs: '日本鬼', jpn: '', eng: 'Japanese Oni'),
  LocalizedText(chs: '失心之人', jpn: '', eng: 'Soulless One'),
  LocalizedText(chs: '肃正骑士', jpn: '', eng: 'Knight Enforcer'),
  LocalizedText(chs: '自动防卫装置', jpn: '', eng: 'Automated Defense'),
  LocalizedText(chs: '斯芬克斯', jpn: '', eng: 'Sphinx'),
  LocalizedText(chs: '伊夫利塔', jpn: '', eng: 'Efreet'),
  LocalizedText(chs: '寄居蟹', jpn: '', eng: 'Hermit Crab'),
  LocalizedText(chs: '魔猪', jpn: '', eng: 'Demon Boar'),
  LocalizedText(chs: '巨大魔猪', jpn: '', eng: 'Calydonian Boar'),
  // LocalizedText(chs: '迷你小库', jpn: '', eng: ''),
  // LocalizedText(chs: '魔法杖', jpn: '', eng: 'Magical Stick'),
  LocalizedText(chs: '乌利迪姆·冰雪之狼', jpn: '', eng: 'Uridimmu-like'),
  LocalizedText(chs: '蝎狮·乌伽尔·冰雪加姆', jpn: '', eng: 'Ugallu-like'),
  LocalizedText(chs: '巴西利斯克·穆修胡休', jpn: '', eng: 'Mushussu-like'),
  // LocalizedText(chs: '复合神性戈耳工', jpn: '', eng: ''),
  // LocalizedText(chs: '拉赫穆', jpn: '', eng: ''),
  // LocalizedText(chs: '魔性之女', jpn: '', eng: ''),
  LocalizedText(chs: '小混混·流氓', jpn: '', eng: 'Hoodlum/Yakuza'),
  LocalizedText(chs: '雀蜂', jpn: '', eng: 'Hornet'),
  LocalizedText(chs: '酷吏', jpn: '', eng: 'Atrocious Officer'),
  LocalizedText(chs: '女海盗', jpn: '', eng: 'Female Pirate'),
  LocalizedText(chs: '许德拉·大蛇', jpn: '', eng: 'Hydra'),
  // LocalizedText(chs: '古伽兰那', jpn: '', eng: ''),
  LocalizedText(chs: '黑武者', jpn: '', eng: 'Black Samurai'),
  // LocalizedText(chs: '量产型机械伊丽亲', jpn: '', eng: ''),
  LocalizedText(chs: '食尸鬼', jpn: '', eng: 'Ghoul'),
  LocalizedText(chs: '灰狼', jpn: '', eng: 'Grey Wolf'),
  LocalizedText(chs: '夏塔克鸟', jpn: '', eng: 'Shantak'),
  // LocalizedText(chs: '邪恶迦鲁拉灵', jpn: '', eng: ''),
  LocalizedText(chs: '杀戮猎兵', jpn: '', eng: 'Oprichnik'),
  // LocalizedText(chs: '伊凡雷帝', jpn: '', eng: ''),
  LocalizedText(chs: '空想树', jpn: '', eng: 'Tree of Emptiness'),
  LocalizedText(chs: '雅嘎', jpn: '', eng: 'Yaga'),
  // LocalizedText(chs: '拟态天之杯', jpn: '', eng: ''),
  // LocalizedText(chs: '英灵兵', jpn: '', eng: ''),
  // LocalizedText(chs: '黑巨人', jpn: '', eng: ''),
  LocalizedText(chs: '巨人', jpn: '', eng: 'Hrimthurse'),
  LocalizedText(chs: '瓦尔基里', jpn: '', eng: 'Walkure'),
  LocalizedText(chs: '斩首鸡', jpn: '', eng: 'Chicken'),
  LocalizedText(chs: '禁卫兵', jpn: '', eng: 'Royal Guard'),
  LocalizedText(chs: '多多益善号', jpn: '', eng: 'The More The Merrier'),
  LocalizedText(chs: '鵺·秽神', jpn: '', eng: 'Nue'),
  LocalizedText(chs: '魔猿', jpn: '', eng: 'Demonic Monkey'),
  // LocalizedText(chs: '女官', jpn: '', eng: ''),
  // LocalizedText(chs: '迦摩/魔罗', jpn: '', eng: ''),
  // LocalizedText(chs: '谟涅摩叙涅', jpn: '', eng: ''),
  // LocalizedText(chs: '庄严的石像', jpn: '', eng: ''),
  LocalizedText(chs: '迦利', jpn: '', eng: 'Kali'),
  LocalizedText(chs: '伟大那伽', jpn: '', eng: 'Mahanaga'),
  // LocalizedText(chs: '柴田胜家', jpn: '', eng: ''),
  LocalizedText(chs: '亚特兰蒂斯防卫兵', jpn: '', eng: 'Atlantean'),
  LocalizedText(chs: '刻耳柏洛斯', jpn: '', eng: 'Cerbernus'),
  LocalizedText(chs: '广域歼灭兵器', jpn: '', eng: 'Wide-Area Ordnace'),
  // LocalizedText(chs: '真体机神', jpn: '', eng: ''),
  LocalizedText(chs: '奥林波斯士兵', jpn: '', eng: 'Olympian Soldier'),
  // LocalizedText(chs: '塔罗斯', jpn: '', eng: ''),
  // LocalizedText(chs: '『玩赏之兽』', jpn: '', eng: ''),
  // LocalizedText(chs: '帮佣人偶', jpn: '', eng: ''),
  // LocalizedText(chs: '芹泽鸭', jpn: '', eng: ''),
  // LocalizedText(chs: '不可视的敌意', jpn: '', eng: ''),
  // LocalizedText(chs: '敌舰阿尔法', jpn: '', eng: ''),
  LocalizedText(chs: '土蜘蛛', jpn: '', eng: 'Tsuchigumo'),
  // LocalizedText(chs: '罗刹王·髑髅乌帽子芦屋道满', jpn: '', eng: ''),
  // LocalizedText(chs: '弗栗多之魔', jpn: '', eng: ''),
  LocalizedText(chs: '蛇', jpn: '', eng: 'Bhujanga'),
  // LocalizedText(chs: '鸦天狗', jpn: '', eng: ''),
  // LocalizedText(chs: '超宝宝卡莲', jpn: '', eng: ''),
  LocalizedText(chs: '死神', jpn: '', eng: 'Mors'),
  LocalizedText(chs: '摩根士兵', jpn: '', eng: 'Queen\'s Soldier'),
  // LocalizedText(chs: '灾厄', jpn: '', eng: ''),
  // LocalizedText(chs: '亚铃百种', jpn: '', eng: ''),
]);
