part of localized;

final _localizedMasterMission = LocalizedGroup([
  LocalizedText(chs: '从者', jpn: 'サーヴァント', eng: 'Servant'),
  LocalizedText(chs: '剑阶', jpn: 'セイバー', eng: 'Saber'),
  LocalizedText(chs: '弓阶', jpn: 'アーチャー', eng: 'Archer'),
  LocalizedText(chs: '枪阶', jpn: 'ランサー', eng: 'Lancer'),
  LocalizedText(chs: '骑阶', jpn: 'ライダー', eng: 'Rider'),
  LocalizedText(chs: '术阶', jpn: 'チャスター', eng: 'Caster'),
  LocalizedText(chs: '杀阶', jpn: 'アサシン', eng: 'Assassin'),
  LocalizedText(chs: '狂阶', jpn: 'バーサーカー', eng: 'Berserker'),
  LocalizedText(chs: '裁阶', jpn: 'ルーラー', eng: 'Ruler'),
  LocalizedText(chs: '仇阶', jpn: 'アヴェンジャー', eng: 'Avenger'),

  LocalizedText(chs: '『天』之力', jpn: '『天』の力', eng: 'Attribute Sky'),
  LocalizedText(chs: '『地』之力', jpn: '『地』の力', eng: 'Attribute Earth'),
  LocalizedText(chs: '『人』之力', jpn: '『人』の力', eng: 'Attribute Man'),
  LocalizedText(chs: '『星』之力', jpn: '『星』の力', eng: 'Attribute Star'),
  ..._localizedGender.values,
  ..._localizedSvtFilter.values,
  // Localized(chs: '女性', jpn: '', eng: 'Female'),
  // Localized(chs: '男性', jpn: '', eng: 'Male'),
  // Localized(chs: '其他性别', jpn: '', eng: ''),
  LocalizedText(chs: '『秩序』属性', jpn: '', eng: 'Alignment Lawful'),
  LocalizedText(chs: '『混沌』属性', jpn: '', eng: 'Alignment Chaotic'),
  LocalizedText(chs: '『中立』属性', jpn: '', eng: 'Alignment Neutral'),
  LocalizedText(chs: '『善』属性', jpn: '', eng: 'Alignment Good'),
  LocalizedText(chs: '『恶』属性', jpn: '', eng: 'Alignment Evil'),
  LocalizedText(chs: '『中庸』属性', jpn: '', eng: 'Alignment Balanced'),
  LocalizedText(chs: '『狂』属性', jpn: '', eng: 'Alignment Mad'),

  // LocalizedText(chs: '龙', jpn: '竜', eng: 'Dragon'),
  // LocalizedText(chs: '骑乘', jpn: '', eng: ''),
  // LocalizedText(chs: '神性', jpn: '神性', eng: 'Divine'),
  // LocalizedText(chs: '猛兽', jpn: '猛獸', eng: 'Beast'),
  // LocalizedText(chs: '王', jpn: '王', eng: 'King'),
  // LocalizedText(chs: '罗马', jpn: '', eng: ''),
  // LocalizedText(chs: '呆毛脸', jpn: '', eng: ''),
  // LocalizedText(chs: '所爱之人', jpn: '', eng: ''),
  // LocalizedText(chs: '希腊神话系男性', jpn: '', eng: ''),
  // LocalizedText(chs: '阿耳戈船相关人员', jpn: '', eng: ''),
  // LocalizedText(chs: '魔性', jpn: '魔性', eng: 'Demonic'),
  // LocalizedText(chs: '天地从者', jpn: '', eng: ''),
  // LocalizedText(chs: '人型', jpn: '人型', eng: 'Humanoid'),

  LocalizedText(chs: '人类', jpn: '', eng: 'Human'),
  LocalizedText(chs: '和风', jpn: '和風', eng: 'Japanese'),
  LocalizedText(chs: '太阳', jpn: '', eng: 'Sun'),
  LocalizedText(chs: '幸运A+以上', jpn: '幸運A+', eng: 'Lucky A+'),
  LocalizedText(chs: '哈桑系', jpn: '', eng: 'Hassan'),
  // LocalizedText(chs: '犬型', jpn: '', eng: ''),
  // LocalizedMessage(chs: '阿斯克勒庇俄斯', jpn: '', eng: ''),
  // LocalizedMessage(chs: '马嘶', jpn: '', eng: ''),

  // enemy traits
  LocalizedText(chs: '小怪', jpn: 'エネミー', eng: 'Enemy'),

  // LocalizedMessage(chs: '女性', jpn: '', eng: ''),
  // LocalizedMessage(chs: '男性', jpn: '', eng: ''),
  // LocalizedMessage(chs: '王', jpn: '', eng: ''),
  // LocalizedMessage(chs: '魔性', jpn: '', eng: ''),
  // LocalizedMessage(chs: '人型', jpn: '', eng: ''),
  // LocalizedMessage(chs: '人类', jpn: '', eng: ''),
  // LocalizedMessage(chs: '神性', jpn: '', eng: ''),
  // LocalizedMessage(chs: '希腊神话系男性', jpn: '', eng: ''),
  // LocalizedMessage(chs: '猛兽', jpn: '', eng: ''),
  // LocalizedMessage(chs: '『恶』属性', jpn: '', eng: ''),
  // Localized(chs: '龙', jpn: '', eng: ''),

  LocalizedText(chs: '死灵', jpn: '', eng: 'Undead'),
  LocalizedText(chs: '犬型', jpn: '', eng: 'Dog'),
  LocalizedText(chs: '罗马', jpn: '', eng: 'Roman'),
  LocalizedText(chs: '恶魔', jpn: '悪魔', eng: 'Demon'),
  LocalizedText(chs: '超巨大', jpn: '超巨大', eng: 'Super Large'),

  LocalizedText(chs: '门系', jpn: '', eng: 'Door'),
  LocalizedText(chs: '骷髅系', jpn: '', eng: 'Skeleton'),
  LocalizedText(chs: '士兵系', jpn: '', eng: 'Soldier'),
  LocalizedText(chs: '双足飞龙系', jpn: '', eng: 'Wyvern'),
  LocalizedText(chs: '僵尸系', jpn: '', eng: 'Zombie'),
  LocalizedText(chs: '兽人系', jpn: '', eng: 'Were-Animals'),
  LocalizedText(chs: '魔偶系', jpn: '', eng: 'Golem'),
  LocalizedText(chs: '鬼魂系', jpn: '', eng: 'Ghost'),
  LocalizedText(chs: '奇美拉系', jpn: '', eng: 'Chimera'),
  LocalizedText(chs: '寄居蟹系', jpn: '', eng: 'Hermit Crab'),
  LocalizedText(chs: '蛇女系', jpn: '', eng: 'Lamia'),
  LocalizedText(chs: '半人马系', jpn: '', eng: 'Centaur'),
  LocalizedText(chs: '亚马逊系', jpn: '', eng: 'Amazoness'),
  LocalizedText(chs: '自动人偶系', jpn: '', eng: 'Automata'),
  LocalizedText(chs: '人工生命体系', jpn: '', eng: 'Homunculus'),
  LocalizedText(chs: '书页系', jpn: '', eng: 'Book'),
  LocalizedText(chs: '混沌机械兵系', jpn: '', eng: 'Helter Skelter'),
  LocalizedText(chs: '机械化步兵系', jpn: '', eng: 'Mechanized Infantry'),
  LocalizedText(chs: '凯尔特士兵系', jpn: '', eng: 'Celtic Soldier'),
  LocalizedText(chs: '噬魂者系', jpn: '', eng: 'Soul Easter'),
  LocalizedText(chs: '凝视者系', jpn: '', eng: 'Gazer'),
  LocalizedText(chs: '双角兽系', jpn: '', eng: 'Bicorn'),
  LocalizedText(chs: '守护者系', jpn: '', eng: 'Spriggan'),
  LocalizedText(chs: '斯芬克斯系', jpn: '', eng: 'Sphinx'),
  LocalizedText(chs: '伊夫利塔系', jpn: '', eng: 'Efreet'),
  LocalizedText(chs: '失心者系', jpn: '', eng: 'Soulless One'),
  LocalizedText(chs: '骑士系', jpn: '', eng: 'Knight'),
  LocalizedText(chs: '自动防卫装置系', jpn: '', eng: 'Automated Defense Unit'),
  LocalizedText(chs: '乌利迪姆系', jpn: '', eng: 'Uridimmu'),
  LocalizedText(chs: '乌伽尔系', jpn: '', eng: 'Ugallu'),
  LocalizedText(chs: '穆修胡休系', jpn: '', eng: 'Mušḫuššu'),
  LocalizedText(chs: '海魔系', jpn: '', eng: 'Sea Demon'),
  LocalizedText(chs: '巨龙系', jpn: '', eng: 'Great Dragon'),
  LocalizedText(chs: '魔猪系', jpn: '', eng: 'Demon Boar'),
  LocalizedText(chs: '巨大魔猪系', jpn: '', eng: 'Calydonian Boar'),
  LocalizedText(chs: '小混混系', jpn: '', eng: 'Hoodlum'),
  LocalizedText(chs: '雀蜂系', jpn: '', eng: 'Hornet'),
  LocalizedText(chs: '流氓系', jpn: '', eng: 'Yakuza'),
  LocalizedText(chs: '恶魔系', jpn: '', eng: 'Daemon'),
  LocalizedText(chs: '女海盗系', jpn: '', eng: 'Female Pirate'),
  LocalizedText(chs: '酷吏系', jpn: '', eng: 'Atrocious Officer'),
  LocalizedText(chs: '许德拉系', jpn: '', eng: 'Hydra'),
  LocalizedText(chs: '黑武者系', jpn: '', eng: 'Black Samurai'),
  LocalizedText(chs: '祟鬼系', jpn: '', eng: 'Cursed Oni'),
  LocalizedText(chs: '秽神系', jpn: '', eng: 'Corrupted God'),
  LocalizedText(chs: '灰狼系', jpn: '', eng: 'Grey Wolf'),
  LocalizedText(chs: '食尸鬼系', jpn: '', eng: 'Ghoul'),
  LocalizedText(chs: '夏塔克鸟系', jpn: '', eng: 'Shantak'),
  LocalizedText(chs: '雅嘎系', jpn: '', eng: 'Yaga'),
  LocalizedText(chs: '杀戮猎兵系', jpn: '', eng: 'Oprichnik'),
  LocalizedText(chs: '巨人系', jpn: '', eng: 'Jötunn'),
  LocalizedText(chs: '瓦尔基里系', jpn: '', eng: 'Walküre'),
  LocalizedText(chs: '坦克系', jpn: '', eng: 'Tank'),
  LocalizedText(chs: '禁卫兵系', jpn: '', eng: 'Royal Guard'),
  LocalizedText(chs: '迦利系', jpn: '', eng: 'Kali'),
  LocalizedText(chs: '亡者系', jpn: '', eng: 'Deceased One'),
  LocalizedText(chs: '伟大那伽系', jpn: '', eng: 'Mahānaga'),
  LocalizedText(chs: '刻耳柏洛斯系', jpn: '', eng: 'Cerberus'),
  LocalizedText(chs: '亚特兰蒂斯防卫兵系', jpn: '', eng: 'Atlantean Defense Troop'),
  LocalizedText(
      chs: '广域歼灭兵器系', jpn: '', eng: 'Wide-Area Annihilation Ordnance'),
  LocalizedText(chs: '奥林波斯兵系', jpn: '', eng: 'Olympian Soldier'),

  // fields
  LocalizedText(chs: '场地', jpn: 'フィールド', eng: 'Field'),
  LocalizedText(chs: '燃烧', jpn: '炎上', eng: 'Flaming'),
  LocalizedText(chs: '都市', jpn: '都市', eng: 'City'),
  LocalizedText(chs: '城市', jpn: '街', eng: 'Street'), // not verified
  LocalizedText(chs: '地下', jpn: '地下', eng: 'Underground'), // not verified
  LocalizedText(chs: '阳光', jpn: '陽射し', eng: 'Sunlight'),
  LocalizedText(chs: '山丘', jpn: '丘', eng: 'Hill'),
  LocalizedText(chs: '森林', jpn: '森', eng: 'Forest'),
  LocalizedText(chs: '城池', jpn: '城', eng: 'Castle'),
  LocalizedText(chs: '荒野', jpn: '荒野', eng: 'Wilderness'),
  LocalizedText(chs: '山', jpn: '山', eng: 'Mountain'), // not verified
  LocalizedText(chs: '水边', jpn: '水辺', eng: 'Waterside'),
  LocalizedText(chs: '沙滩·沙漠', jpn: '砂浜・砂漠', eng: 'Beach/Desert'),
  LocalizedText(chs: '神殿', jpn: '神殿', eng: 'Shrine'),
  LocalizedText(chs: '岩山', jpn: '岩山', eng: 'Rocky Mountain'),
  LocalizedText(chs: '草原', jpn: '草原', eng: 'Prairie'),
]);
