part of localized;

const _enemy = LocalizedGroup([
  LocalizedText(
      chs: '影从者', jpn: 'シャドウサーヴァント', eng: 'Shadow Servant', kor: '섀도 서번트'),
  LocalizedText(chs: '亡者之门', jpn: '', eng: 'Door of the Undead', kor: '망자의 문'),
  LocalizedText(chs: '勇者之门', jpn: '', eng: 'Door of Brave', kor: '용사의 문'),
  LocalizedText(chs: '圣者之门', jpn: '', eng: 'Door of Saint', kor: '성자의 문'),
  LocalizedText(chs: '霸者之门', jpn: '', eng: 'Door of Champion', kor: '패자의 문'),
  LocalizedText(chs: '黎明之手', jpn: '', eng: 'Hand of Dawn', kor: '여명의 손'),
  LocalizedText(chs: '黎明之腕', jpn: '', eng: 'Arm of Dawn', kor: '여명의 팔'),
  LocalizedText(
      chs: '黎明之刚腕', jpn: '', eng: 'Strong Arm of Dawn', kor: '여명의 강완'),
  LocalizedText(
      chs: '黎明之神腕', jpn: '', eng: 'Divine Arm of Dawn', kor: '여명의 신완'),
  LocalizedText(
      chs: '黎明之炎腕', jpn: '', eng: 'Radiant Arm of Dawn', kor: '여명의 염완'),
  LocalizedText(chs: '圣诞之手', jpn: '', eng: 'Christmas Hand', kor: '프레젠트 핸드'),
  LocalizedText(chs: '圣诞手套', jpn: '', eng: 'Christmas Glove', kor: '크리스마스 글러브'),
  LocalizedText(chs: '圣诞之拳', jpn: '', eng: 'Christmas Fist', kor: '크리스마스 피스트'),
  LocalizedText(chs: '驱鬼之手', jpn: '', eng: '', kor: '귀신을 쫓는 손'),
  LocalizedText(chs: '骷髅兵', jpn: '', eng: 'Skeleton', kor: '스켈레톤'),
  LocalizedText(
      chs: '南瓜骷髅兵', jpn: '', eng: 'Pumpkin Skeleton', kor: '펌프킨 스켈레톤'),
  LocalizedText(chs: '骸骨之王', jpn: '', eng: 'Skeleton King', kor: '스켈레톤 킹'),
  LocalizedText(
      chs: '金属南瓜骷髅兵',
      jpn: '',
      eng: 'Metal Pumpkin Skeleton',
      kor: '메탈 펌프킨 스켈레톤'),
  LocalizedText(chs: '龙牙兵', jpn: '', eng: 'Dragon Tooth Warrior', kor: '용아병'),
  LocalizedText(chs: '古代兵', jpn: '', eng: 'Ancient Soldier', kor: '고대 병사'),
  LocalizedText(chs: '古代兵僵尸', jpn: '', eng: 'Ancient Zombie', kor: '고대 병사 좀비'),
  LocalizedText(chs: '联合罗马士兵', jpn: '', eng: 'Roman Soldier', kor: '연합 로마 병사'),
  LocalizedText(chs: '罗马士兵', jpn: '', eng: 'Roman Soldier', kor: '로마 병사'),
  LocalizedText(chs: '中世兵', jpn: '', eng: 'Medieval Soldier', kor: '중세 병사'),
  LocalizedText(chs: '中世兵僵尸', jpn: '', eng: 'Medieval Zombie', kor: '중세 병사 좀비'),
  LocalizedText(chs: '法国士兵', jpn: '', eng: 'French Soldier', kor: '프랑스 병사'),
  LocalizedText(chs: '近代兵', jpn: '', eng: 'Pre-Modern Soldier', kor: '근대 병사'),
  LocalizedText(
      chs: '近代兵僵尸', jpn: '', eng: 'Pre-Modern Zombie', kor: '근대 병사 좀비'),
  LocalizedText(chs: '海盗', jpn: '', eng: 'Pirate', kor: '해적'),
  LocalizedText(
      chs: '从者庆典参加者', jpn: '', eng: 'Serva Fes Attendee', kor: '서버페스 참가자'),
  LocalizedText(chs: '僵尸', jpn: '', eng: 'Zombie', kor: '좀비'),
  LocalizedText(chs: '海盗僵尸', jpn: '', eng: 'Pirate Zombie', kor: '해적 좀비'),
  LocalizedText(chs: '鬼魂', jpn: '', eng: 'Ghost', kor: '고스트'),
  LocalizedText(chs: '恐怖鬼魂', jpn: '', eng: 'Terror Ghost', kor: '테러 고스트'),
  LocalizedText(chs: '古代鬼魂', jpn: '', eng: 'Ancient Ghost', kor: '에인션트 고스트'),
  LocalizedText(chs: '稻草人', jpn: '', eng: 'Scarecrow', kor: '허수아비'),
  LocalizedText(chs: '忌灵', jpn: '', eng: 'Abhor Soul', kor: '기령'),
  LocalizedText(chs: '金属稻草人', jpn: '', eng: 'Metal Scarecrow', kor: '메탈 허수아비'),
  LocalizedText(chs: '派对鬼魂', jpn: '', eng: 'Gallû Spirit', kor: '가루라령'),
  LocalizedText(chs: '假面鬼魂', jpn: '', eng: 'Mask Ghost', kor: '마스크 고스트'),
  LocalizedText(chs: '蒸汽鬼魂', jpn: '', eng: 'Steam Ghost', kor: '스팀 고스트'),
  LocalizedText(chs: '恶魔', jpn: '', eng: 'Demon', kor: '데몬'),
  LocalizedText(chs: '上级恶魔', jpn: '', eng: 'Greater Demon', kor: '그레이터 데몬'),
  LocalizedText(chs: '高等恶魔', jpn: '', eng: 'Archdemon', kor: '아크 데몬'),
  LocalizedText(chs: '自动人偶', jpn: '', eng: 'Automata', kor: '오토마타'),
  LocalizedText(chs: '杀戮人偶', jpn: '', eng: 'Killing Doll', kor: '킬링 돌'),
  LocalizedText(chs: '陈旧装置', jpn: '', eng: 'Old Gear', kor: '올드 기어'),
  LocalizedText(chs: '花腔歌手', jpn: '', eng: 'Coloratura', kor: '콜로라투라'),
  LocalizedText(chs: '克里斯蒂娜', jpn: '', eng: 'Christine', kor: '크리스틴'),
  LocalizedText(chs: '傀儡兵', jpn: '', eng: 'Terracotta Warrior', kor: '괴뢰병'),
  LocalizedText(
      chs: '古董自动人偶', jpn: '', eng: 'Antique Automata', kor: '앤틱 오토마타'),
  LocalizedText(chs: '假面自动人偶', jpn: '', eng: 'Mask Automata', kor: '마스크 오토마타'),
  LocalizedText(
      chs: '对人歼灭装置',
      jpn: '',
      eng: 'Anti-Personnel Annihilation Device',
      kor: '대인 섬멸 장치'),
  LocalizedText(chs: '魔偶', jpn: '', eng: 'Golem', kor: '골렘'),
  LocalizedText(chs: '石魔偶', jpn: '', eng: 'Stone Golem', kor: '스톤 골렘'),
  LocalizedText(chs: '金属魔偶', jpn: '', eng: 'Iron Golem', kor: '아이언 골렘'),
  LocalizedText(chs: '水晶魔偶', jpn: '', eng: 'Crystal Golem', kor: '크리스탈 골렘'),
  LocalizedText(chs: '红宝石魔偶', jpn: '', eng: 'Ruby Golem', kor: '루비 골렘'),
  LocalizedText(
      chs: '双子钢铁魔偶', jpn: '', eng: 'Twin Steel Golem', kor: '트윈 스틸 골렘'),
  LocalizedText(chs: '雪人', jpn: '', eng: 'Snowman', kor: '스노우맨'),
  LocalizedText(chs: '巨型雪人', jpn: '', eng: 'Giant Snowman', kor: '자이언트 스노우맨'),
  LocalizedText(chs: '饼干魔偶', jpn: '', eng: 'Biscuit Golem', kor: '비스킷 골렘'),
  LocalizedText(chs: '阿维斯布隆魔偶', jpn: '', eng: 'Golem', kor: '아비케브론 골렘'),
  LocalizedText(chs: '双足飞龙', jpn: '', eng: 'Wyvern', kor: '와이번'),
  LocalizedText(chs: '恐惧飞龙', jpn: '', eng: 'Wyvern Dread', kor: '와이번 드레드'),
  LocalizedText(chs: '恶魔飞龙', jpn: '', eng: 'Wyvern Evil', kor: '와이번 이블'),
  LocalizedText(chs: '古代飞龙', jpn: '', eng: 'Wyvern Classic', kor: '와이번 클래식'),
  LocalizedText(chs: '原始双足飞龙', jpn: '', eng: 'Wyvern Origin', kor: '와이번 오리진'),
  LocalizedText(chs: '彩虹双足飞龙', jpn: '', eng: 'Rainbow Wyvern', kor: '레인보우 와이번'),
  LocalizedText(chs: '风暴双足飞龙', jpn: '', eng: 'Wyvern Tempest', kor: '와이번 템페스트'),
  LocalizedText(chs: '龙', jpn: '', eng: 'Dragon', kor: '드래곤'),
  LocalizedText(chs: '巨龙', jpn: '', eng: 'Great Dragon', kor: '그레이트 드래곤'),
  LocalizedText(chs: '长老龙', jpn: '', eng: 'Primeval Dragon', kor: '엘더 드래곤'),
  LocalizedText(chs: '太古龙', jpn: '', eng: 'Elder Dragon', kor: '엘더 드래곤'),
  LocalizedText(chs: '法夫纳', jpn: '', eng: 'Fafnir', kor: '파프니르'),
  LocalizedText(chs: '巴修穆', jpn: '', eng: 'Bašmu', kor: '바슈무'),
  LocalizedText(chs: '黄金龙', jpn: '', eng: 'Golden Dragon', kor: '황금용'),
  LocalizedText(chs: '亚马逊人', jpn: '', eng: 'Amazoness', kor: '아마조네스'),
  LocalizedText(
      chs: '亚马逊队长', jpn: '', eng: 'Amazoness Leader', kor: '아마조네스 리더'),
  LocalizedText(
      chs: '亚马逊女王', jpn: '', eng: 'Amazoness Queen', kor: '아마조네스 엘리트'),
  LocalizedText(chs: '蛇女', jpn: '', eng: 'Lamia', kor: '라미아'),
  LocalizedText(chs: '那伽', jpn: '', eng: 'Naga', kor: '나가'),
  LocalizedText(chs: '那伽王', jpn: '', eng: 'Naga Raja', kor: '나가라자'),
  LocalizedText(chs: '蛇女女王', jpn: '', eng: 'Lamia Queen', kor: '라미아 퀸'),
  LocalizedText(chs: '原始蛇女', jpn: '', eng: 'Origin Lamia', kor: '오리진 라미아'),
  LocalizedText(chs: '半人马', jpn: '', eng: 'Centaur', kor: '켄타우로스'),
  LocalizedText(chs: '半人马骑士', jpn: '', eng: 'Centaur Knight', kor: '켄타우로스 나이트'),
  LocalizedText(
      chs: '半人马圣骑', jpn: '', eng: 'Centaur Paladin', kor: '켄타우로스 팔라딘'),
  LocalizedText(chs: '奇美拉', jpn: '', eng: 'Chimera', kor: '키메라'),
  LocalizedText(chs: '白色奇美拉', jpn: '', eng: 'White Chimera', kor: '화이트 키메라'),
  LocalizedText(chs: '超级奇美拉', jpn: '', eng: 'Super Chimera', kor: '슈퍼 키메라'),
  LocalizedText(chs: '达温', jpn: '', eng: 'Gdon', kor: '다원'),
  LocalizedText(chs: '原始奇美拉', jpn: '', eng: 'Origin Chimera', kor: '오리진 키메라'),
  LocalizedText(chs: '咒语书', jpn: '', eng: 'Spellbook', kor: '스펠북'),
  LocalizedText(chs: '雷电咒书', jpn: '', eng: 'Thunder Book', kor: '썬더 북'),
  LocalizedText(chs: '火焰咒书', jpn: '', eng: 'Fire Book', kor: '파이어 북'),
  LocalizedText(chs: '疾风咒书', jpn: '', eng: 'Wind Bood', kor: '윈드 북'),
  LocalizedText(chs: '冰雪咒书', jpn: '', eng: 'Ice Book', kor: '아이스 북'),
  LocalizedText(chs: '魔导书', jpn: '', eng: 'Grimoire', kor: '그리모어'),
  LocalizedText(chs: '大魔道书', jpn: '', eng: 'Greater Grimoire', kor: '대마도서'),
  LocalizedText(chs: '咒本', jpn: '', eng: 'Japanese Anthology Book', kor: '주서'),
  LocalizedText(
      chs: '最初的咒本', jpn: '', eng: 'Primeval Accursed Book', kor: '최초의 주서'),
  LocalizedText(chs: '人工生命体', jpn: '', eng: 'Homunculus', kor: '호문쿨루스'),
  LocalizedText(
      chs: '人工生命体原型', jpn: '', eng: 'Proto Homunculus', kor: '프로토 호문쿨루스'),
  LocalizedText(chs: '狼人', jpn: '', eng: 'Werewolf', kor: '웨어울프'),
  LocalizedText(chs: '豹人', jpn: '', eng: 'Werejaguar', kor: '웨어재규어'),
  LocalizedText(chs: '哥布林', jpn: '', eng: 'Goblin', kor: '고블린'),
  LocalizedText(chs: '驯鹿人', jpn: '', eng: 'Reindeer Man', kor: '순록맨'),
  LocalizedText(
      chs: '巨型驯鹿人', jpn: '', eng: 'Great Reindeer Man', kor: '그레이트 순록맨'),
  LocalizedText(
      chs: '超级驯鹿人', jpn: '', eng: 'Super Reindeer Man', kor: '슈퍼 순록맨'),
  LocalizedText(chs: '混沌机械兵', jpn: '', eng: 'Helter Skelter', kor: '헬터 스켈터'),
  LocalizedText(chs: '南瓜无人机', jpn: '', eng: 'Pumpkin Drone', kor: '펌프킨 드론'),
  LocalizedText(
      chs: '西装尸人', jpn: '', eng: 'Business Suit Undead', kor: '양복 차림의 시체'),
  LocalizedText(chs: '背心尸人', jpn: '', eng: 'Tank top Undead', kor: '탱크톱 시체'),
  LocalizedText(chs: 'DeadMan', jpn: '', eng: 'DeadMan', kor: 'DeadMan'),
  LocalizedText(
      chs: '七人御佐姬',
      jpn: '',
      eng: 'Vengeful Spirit of Seven People',
      kor: '7인의 망령'),
  LocalizedText(chs: '长发公主', jpn: '', eng: 'Rapunzel', kor: '라푼젤'),
  LocalizedText(chs: '大无间地狱堂', jpn: '', eng: 'Massive Ghost', kor: '대무간지옥당'),
  LocalizedText(chs: '不净观太极殿', jpn: '', eng: 'Massive Ghost', kor: '부정관태극전'),
  LocalizedText(
      chs: '通晓恩怨的魂之集群', jpn: '', eng: 'Massive Ghost', kor: '은원을 아는 혼의 무리'),
  LocalizedText(chs: '烟醉哈桑', jpn: '', eng: 'Massive Ghost', kor: '연취의 하산'),
  LocalizedText(chs: '鸣钟之物', jpn: '', eng: 'Massive Ghost', kor: '종을 울리는 자'),
  LocalizedText(chs: '巨大鬼魂', jpn: '', eng: 'Massive Ghost', kor: '휴즈 고스트'),
  LocalizedText(
      chs: '罗密欧与朱丽叶', jpn: '', eng: 'Romeo and Juliet', kor: '로미오와 줄리엣'),
  LocalizedText(chs: '谜题', jpn: '', eng: 'Enigma', kor: '에니그마'),
  LocalizedText(chs: '边狱大灵', jpn: '', eng: 'Limbo', kor: '림보'),
  LocalizedText(chs: '女官鬼魂', jpn: '', eng: 'Lynchpin Maid', kor: '시녀 고스트'),
  LocalizedText(
      chs: '巨大蒸汽鬼魂', jpn: '', eng: 'Massive Stram Ghost', kor: '거대 스팀 고스트'),
  LocalizedText(chs: '徐福', jpn: '', eng: 'Xu Fu', kor: '서복'),
  LocalizedText(chs: '守护者', jpn: '', eng: 'Spriggan', kor: '스프리건'),
  LocalizedText(chs: '青铜守护者', jpn: '', eng: 'Bronze Spriggan', kor: '브론즈 스프리건'),
  LocalizedText(chs: '李尔王', jpn: '', eng: 'King Lear', kor: '리어 왕'),
  LocalizedText(chs: '双角兽', jpn: '', eng: 'Bicorn', kor: '바이콘'),
  LocalizedText(chs: '双角兽之王', jpn: '', eng: 'Emperorcorn', kor: '엠퍼러 콘'),
  LocalizedText(chs: '神马高耳', jpn: '', eng: 'Uchchaihshravas', kor: '웃체이슈라바스'),
  LocalizedText(chs: '凝视者', jpn: '', eng: 'Gazer', kor: '게이저'),
  LocalizedText(chs: '观察机', jpn: '', eng: 'Spotter', kor: '스폿터'),
  LocalizedText(chs: '南瓜凝视者', jpn: '', eng: 'Pumpkin Gazer', kor: '호박 게이저'),
  LocalizedText(chs: '噬魂者', jpn: '', eng: 'Soul Eater', kor: '소울이터'),
  LocalizedText(chs: '星之兽', jpn: '', eng: 'Astral Critter', kor: '아스트랄 크리터'),
  LocalizedText(chs: '乌修穆迦尔', jpn: '', eng: 'Ušumgallu', kor: '우슘갈루'),
  LocalizedText(chs: '萨罗摩', jpn: '', eng: 'Sarama', kor: '사라마'),
  LocalizedText(
      chs: '机械化步兵', jpn: '', eng: 'Mechanized Infantry', kor: '기계화 보병'),
  LocalizedText(chs: '凯尔特士兵', jpn: '', eng: 'Celtic Soldier', kor: '켈트 병사'),
  LocalizedText(chs: '德鲁伊', jpn: '', eng: 'Druid', kor: '드루이드'),
  LocalizedText(chs: '看守', jpn: '', eng: 'Warden', kor: '간수'),
  LocalizedText(chs: '小魔', jpn: '', eng: 'Little Demon', kor: '소마'),
  LocalizedText(chs: '海魔', jpn: '', eng: 'Sea Demon', kor: '해마'),
  LocalizedText(chs: '大食海魔', jpn: '', eng: 'Gluttonous Sea Demon', kor: '대식해마'),
  LocalizedText(chs: '穆修玛夫', jpn: '', eng: 'Mušmaḫḫū', kor: '무슈마후'),
  LocalizedText(chs: '翅刃虫', jpn: '', eng: 'Bladed-Wing Insect', kor: '시인충'),
  LocalizedText(chs: '翅刃群虫', jpn: '', eng: 'Bladed-Wing Swarm', kor: '시인군충'),
  LocalizedText(chs: '迅速之马库尔', jpn: '', eng: 'Makuru the Quick', kor: '신속의 마쿨'),
  LocalizedText(chs: '基底之扎伊德', jpn: '', eng: 'Zayd the Base', kor: '기저의 자이드'),
  LocalizedText(
      chs: '怪腕之戈兹尔', jpn: '', eng: 'Remarkable Gozuru', kor: '괴완의 고즐'),
  LocalizedText(chs: '醉酒城里人', jpn: '', eng: 'Drunken Citizen', kor: '취한 교토 사람'),
  LocalizedText(
      chs: '农村亭卒',
      jpn: '',
      eng: 'Agricultural Resident Employee',
      kor: '농촌 주재원'),
  LocalizedText(chs: '鬼之左腕', jpn: '', eng: 'Demon Arm', kor: '오니의 왼팔'),
  LocalizedText(chs: '鬼之右腕', jpn: '', eng: 'Demon Arm', kor: '오니의 오른팔'),
  LocalizedText(chs: '苍雷石', jpn: '', eng: 'Thunder Stone', kor: '창뇌석'),
  LocalizedText(chs: '碧雷石', jpn: '', eng: 'Thunder Stone', kor: '벽뇌석'),
  LocalizedText(chs: '技喰丸', jpn: '', eng: 'Wazahamimaru', kor: '와자하미마루'),
  LocalizedText(chs: '风越丸', jpn: '', eng: 'Kazakoemaru', kor: '카자코에마루'),
  LocalizedText(chs: '轰力丸', jpn: '', eng: 'Gōrikimaru', kor: '고리키마루'),
  LocalizedText(chs: '小鬼', jpn: '', eng: 'Oni lmp', kor: '소귀'),
  LocalizedText(chs: '邪鬼', jpn: '', eng: 'Oni Devil', kor: '사귀'),
  LocalizedText(chs: '祟鬼', jpn: '', eng: 'Cursed Oni', kor: '수귀'),
  LocalizedText(
      chs: '南瓜食人鬼·J', jpn: '', eng: 'Pumpkin Ogre・J', kor: '펌프킨 오거 J'),
  LocalizedText(
      chs: '赤南瓜WAN', jpn: '', eng: 'Red Pumpkin MARU', kor: '붉은 호박MARU'),
  LocalizedText(
      chs: '绿南瓜WAN', jpn: '', eng: 'Green Pumpkin MARU', kor: '초록 호박MARU'),
  LocalizedText(
      chs: '青南瓜WAN', jpn: '', eng: 'Blue Pumpkin MARU', kor: '푸른 호박MARU'),
  LocalizedText(chs: '鬼王朱裸', jpn: '', eng: 'Oni King Shura', kor: '오니왕 슈라'),
  LocalizedText(chs: '虎熊童子', jpn: '', eng: 'Torakuma Dōji', kor: '토라구마도지'),
  LocalizedText(chs: '大翁鬼', jpn: '', eng: 'Hakushikijyo', kor: '대옹귀'),
  LocalizedText(chs: '失心之人', jpn: '', eng: 'Soulless One', kor: '마음을 잃은 자'),
  LocalizedText(chs: '失心罪人', jpn: '', eng: 'Soulless Sinner', kor: '마음을 잃은 죄인'),
  LocalizedText(chs: '亡者', jpn: '', eng: 'Deceased One', kor: '망자'),
  LocalizedText(chs: '杀人鬼', jpn: '', eng: 'Cutthroat', kor: '살인귀'),
  LocalizedText(chs: '肃正骑士', jpn: '', eng: 'Knight Enforcer', kor: '숙정기사'),
  LocalizedText(chs: '南瓜骑士', jpn: '', eng: 'Pumpkin Knight', kor: '펌프킨 나이트 '),
  LocalizedText(
      chs: '金属南瓜骑士', jpn: '', eng: 'Metal Pumpkin Knight', kor: '메탈 펌프킨 나이트'),
  LocalizedText(
      chs: '自动防卫装置', jpn: '', eng: 'Automated Defense Unit', kor: '자동방위장치'),
  LocalizedText(
      chs: '自动防卫装置·二式',
      jpn: '',
      eng: 'Automated Defense Unit Mk-2',
      kor: '자동방위장치·2식'),
  LocalizedText(chs: '舞动的硬币', jpn: '', eng: 'Dancing Coin', kor: '댄싱 코인'),
  LocalizedText(chs: '斯芬克斯', jpn: '', eng: 'Sphinx', kor: '스핑크스'),
  LocalizedText(chs: '女王斯芬克斯', jpn: '', eng: 'Sphinx Queen', kor: '스핑크스 퀸'),
  LocalizedText(chs: '卡夫拉斯芬克斯', jpn: '', eng: 'Khafre Sphinx', kor: '카프레 스핑크스'),
  LocalizedText(chs: '伊夫利塔', jpn: '', eng: 'Efreet', kor: '이프리트'),
  LocalizedText(
      chs: '花之邪神', jpn: '', eng: 'Evil God of the Flower', kor: '알라우네'),
  LocalizedText(chs: '大寄居蟹', jpn: '', eng: 'Giant Hermit Crab', kor: '큰 소라게'),
  LocalizedText(
      chs: '毒寄居蟹', jpn: '', eng: 'Poisonous Hermit Crab', kor: '독 소라게'),
  LocalizedText(
      chs: '千年寄居蟹', jpn: '', eng: 'Millennium Hermit Crab', kor: '천년 소라게'),
  LocalizedText(chs: '破坏兽', jpn: '', eng: 'Razrushat', kor: '라즈루샤띠'),
  LocalizedText(chs: '魔猪', jpn: '', eng: 'Demon Boar', kor: '괴물 멧돼지'),
  LocalizedText(chs: '秽猪', jpn: '', eng: 'Demon Boar', kor: '괴물 멧돼지'),
  LocalizedText(chs: '巨大魔猪', jpn: '', eng: 'Calydonian Boar', kor: '거대 괴물 멧돼지'),
  LocalizedText(
      chs: '机械魔猪', jpn: '', eng: 'Mecha Demon Boar', kor: '메카 괴물 멧돼지'),
  LocalizedText(chs: '迷你小库', jpn: '', eng: 'Mini Cú-chan', kor: '미니 쿠짱'),
  LocalizedText(chs: '魔法杖', jpn: '', eng: 'Magical Stick', kor: '매지컬 스틱'),
  LocalizedText(chs: '魔法杖！', jpn: '', eng: 'Magical Stick!', kor: '매지컬 스틱!'),
  LocalizedText(chs: '魔法杖～', jpn: '', eng: 'Magical Stick~', kor: '매지컬 스틱~'),
  LocalizedText(chs: '魔法杖？', jpn: '', eng: 'Magical Stick?', kor: '매지컬 스틱?'),
  LocalizedText(chs: '乌利迪姆', jpn: '', eng: 'Uridimmu', kor: '우리딤무'),
  LocalizedText(chs: '冰雪之狼', jpn: '', eng: 'Íss Úlfr', kor: '이스 울프르'),
  LocalizedText(chs: '乌伽尔', jpn: '', eng: 'Ugallu', kor: '우갈루'),
  LocalizedText(chs: '蝎狮', jpn: '', eng: 'Manticore', kor: '만티코어'),
  LocalizedText(chs: '冰雪加姆', jpn: '', eng: 'Íss Garmr', kor: '이스 가름'),
  LocalizedText(chs: '穆修胡休', jpn: '', eng: 'Mušḫuššu', kor: '무슈후슈'),
  LocalizedText(chs: '巴西利斯克', jpn: '', eng: 'Basilisk', kor: '바실리스크'),
  LocalizedText(chs: '咆哮兽', jpn: '', eng: 'Krichat\'', kor: '크리차띠'),
  LocalizedText(chs: '仿科摩多巨蜥', jpn: '', eng: 'Pseudo-Komodo Dragon', kor: '피톤'),
  LocalizedText(
      chs: '复合神性戈耳工',
      jpn: '複合神性ゴルゴーン',
      eng: 'Composite Deity Gorgon',
      kor: '복합신성 고르곤'),
  LocalizedText(chs: '拉赫穆', jpn: '', eng: 'Laḫmu', kor: '라흐무'),
  LocalizedText(chs: '巴力拉赫穆', jpn: '', eng: 'Bel Laḫmu', kor: '벨라흐무'),
  LocalizedText(chs: '魔性之女', jpn: '', eng: 'Tiamat', kor: '티아마트'),
  LocalizedText(chs: '小混混', jpn: '', eng: 'Hoodlum', kor: '불량배'),
  LocalizedText(chs: '流氓', jpn: '', eng: 'Yakuza', kor: '야쿠자'),
  LocalizedText(chs: '雀蜂', jpn: '', eng: 'Hornet', kor: '말벌'),
  LocalizedText(chs: '雀蜂1', jpn: '', eng: 'Hornet1', kor: '말벌1'),
  LocalizedText(chs: '雀蜂2', jpn: '', eng: 'Hornet2', kor: '말벌2'),
  LocalizedText(chs: '酷吏', jpn: '', eng: 'Atrocious Officer', kor: '혹리'),
  LocalizedText(chs: '女海盗', jpn: '', eng: 'Female Pirate', kor: '여해적'),
  LocalizedText(chs: '许德拉', jpn: '', eng: 'Hydra', kor: '히드라'),
  LocalizedText(chs: '大蛇', jpn: '', eng: 'Orochi', kor: '오로치'),
  LocalizedText(chs: '恶魔御座', jpn: '', eng: 'D\'yavol Tron', kor: '디야발 뜨란'),
  LocalizedText(chs: '原始许德拉', jpn: '', eng: 'Origin Hydra', kor: '오리진 히드라'),
  LocalizedText(chs: '古伽兰那', jpn: '', eng: 'Gugalanna', kor: '구갈안나'),
  LocalizedText(chs: '黑武者', jpn: '', eng: 'Black Samurai', kor: '검은 무사'),
  LocalizedText(
      chs: '南瓜骑士·J', jpn: '', eng: 'Pumpkin Knight・J', kor: '펌프킨 나이트 J'),
  LocalizedText(
      chs: '暗之新选组队士',
      jpn: '',
      eng: 'Dark Shinsengumi Troop',
      kor: '어둠의 신센구미 병사'),
  LocalizedText(
      chs: '量产型机械伊丽亲',
      jpn: '',
      eng: 'Mass-Produced Mecha Eli-chan',
      kor: '양산형 메카에리쨩'),
  LocalizedText(chs: '食尸鬼', jpn: '', eng: 'Ghoul', kor: '구울'),
  LocalizedText(chs: '食尸鬼·嫉妒', jpn: '', eng: 'Ghoul Prophet', kor: '구울 엔비야'),
  LocalizedText(chs: '食尸鬼·暴食', jpn: '', eng: 'Ghoul Glutton', kor: '구울 글러튼'),
  LocalizedText(chs: '元老食尸鬼', jpn: '', eng: 'Elder Ghoul', kor: '엘더 구울'),
  LocalizedText(chs: '灰狼', jpn: '', eng: 'Grey Wolf', kor: '회색 늑대'),
  LocalizedText(chs: '夏塔克鸟', jpn: '', eng: 'Shantak', kor: '샨타크'),
  LocalizedText(chs: '迦楼罗', jpn: '', eng: 'Garuda', kor: '가루다'),
  LocalizedText(chs: '杀戮猎兵', jpn: '', eng: 'Oprichnik', kor: '살육엽병'),
  LocalizedText(
      chs: '亚种空想树的种子', jpn: '', eng: 'Quixotic Tree Seed', kor: '공상수의 씨앗'),
  LocalizedText(chs: '雅嘎', jpn: '', eng: 'Yaga', kor: '야가'),
  LocalizedText(chs: '英灵兵', jpn: '', eng: 'Heavy Armoured Warrior', kor: '영령병'),
  LocalizedText(
      chs: '魔导僧兵', jpn: '', eng: 'Heretical Warrior Monk', kor: '마도승병'),
  LocalizedText(chs: '黑巨人', jpn: '', eng: 'Black Giant', kor: '검은 거인'),
  LocalizedText(chs: '霜之巨人', jpn: '', eng: 'Hrimthurse', kor: '서리 거인'),
  LocalizedText(chs: '山之巨人', jpn: '', eng: 'Bergrisi', kor: '산 거인'),
  LocalizedText(chs: '火之巨人', jpn: '', eng: 'Múspell', kor: '불 거인'),
  LocalizedText(chs: '苏鲁特', jpn: '', eng: 'Surtr', kor: '수르트'),
  LocalizedText(chs: '苏鲁特·芬里厄', jpn: '', eng: 'Surtr・Fenrir', kor: '수르트 펜리르'),
  LocalizedText(chs: '瓦尔基里', jpn: '', eng: 'Walküre', kor: '발키리'),
  LocalizedText(chs: '斩首鸡', jpn: '', eng: 'Bhopal Chicken', kor: '보팔 치킨'),
  LocalizedText(
      chs: '斩首鸡王', jpn: '', eng: 'King Vorpal Chicken', kor: '킹 보팔 치킨'),
  LocalizedText(chs: '禁卫兵', jpn: '', eng: 'Royal Guard', kor: '근위병'),
  LocalizedText(
      chs: '多多益善号', jpn: '', eng: 'The More The Merrier', kor: '다다익선호'),
  LocalizedText(chs: '鵺', jpn: '', eng: 'Nue', kor: '누에'),
  LocalizedText(chs: '秽神', jpn: '', eng: 'Corrupted God', kor: '부정한 신'),
  LocalizedText(chs: '魔猿', jpn: '', eng: 'Demonic Monkey', kor: '괴물 원숭이'),
  LocalizedText(chs: '温泉魔猿', jpn: '', eng: 'Demonic Monkey', kor: '온천 괴물 원숭이'),
  LocalizedText(chs: '新年魔猿', jpn: '', eng: 'Demonic Monkey', kor: '설날 괴물 원숭이'),
  LocalizedText(chs: '包袱布魔猿', jpn: '', eng: 'Demonic Monkey', kor: '허풍 괴물 원숭이'),
  LocalizedText(chs: '女官', jpn: '', eng: 'Ōoku Jochū', kor: '시녀'),
  LocalizedText(chs: '上级女官', jpn: '', eng: 'Senior Jochū', kor: '상급 시녀'),
  LocalizedText(
      chs: '庄严的石像', jpn: '', eng: 'Statue of Gratitude', kor: '고마운 석상'),
  LocalizedText(chs: '迦利', jpn: '', eng: 'Kali', kor: '칼리'),
  LocalizedText(chs: '迦利·集合体', jpn: '', eng: 'Kali Sangha', kor: '칼리 상가'),
  LocalizedText(chs: '伟大那伽', jpn: '', eng: 'Mahānaga', kor: '마하나가'),
  LocalizedText(
      chs: '亚特兰蒂斯防卫兵',
      jpn: '',
      eng: 'Atlantean Defense Troop',
      kor: '아틀란티스의 수비병'),
  LocalizedText(chs: '原型', jpn: '', eng: 'Prototype', kor: '프로토타입'),
  LocalizedText(chs: '刻耳柏洛斯', jpn: '', eng: 'Cerberus', kor: '케르베로스'),
  LocalizedText(
      chs: '广域歼灭兵器',
      jpn: '',
      eng: 'Wide-Area Annihilation Ordnance',
      kor: '광역 섬멸 병기'),
  LocalizedText(
      chs: '奥林波斯士兵', jpn: '', eng: 'Olympian Soldier', kor: '올림포스 병사'),
  LocalizedText(chs: '女佣娃娃', jpn: '', eng: 'Helper Doll', kor: '도우미 인형'),
  LocalizedText(chs: '土蜘蛛', jpn: '', eng: 'Tsuchigumo', kor: '츠치구모'),
  LocalizedText(
      chs: '大土蜘蛛·玖贺耳之御笠', jpn: '', eng: 'Great Tsuchigumo', kor: '오오츠치구모'),
  // 2.6
  LocalizedText(chs: '死神', jpn: '', eng: 'Mors', kor: '모스'),
  LocalizedText(chs: '大型死神', jpn: '', eng: 'Large Mors', kor: '대형 모스'),
  LocalizedText(chs: '森の獣', jpn: '森の獣', eng: 'Forest Beast', kor: '숲의 짐승'),
  LocalizedText(chs: '牙之氏族', jpn: '', eng: 'Fang Clan', kor: '송곳니의 씨족'),
  LocalizedText(chs: '眼镜蛇', jpn: 'ブジャンガ', eng: "Bhujanga", kor: '부장가'),
  // LocalizedText(chs: '', jpn: 'よどみ', eng: '', kor: '웅덩이'),
  LocalizedText(chs: '黑犬', jpn: '', eng: 'Black Dog', kor: '블랙 독'),
  LocalizedText(chs: '摩根士兵', jpn: '', eng: "Queen's Soldier", kor: '여왕의 기사'),
  LocalizedText(chs: '死神人类', jpn: '', eng: 'Human-Mors', kor: '모스 인간'),
  LocalizedText(chs: '王之氏族', jpn: '', eng: 'Royal Clan', kor: '왕의 씨족'),
  LocalizedText(
      chs: '王之氏族·小兵', jpn: '', eng: 'Royal Clan・Veteran', kor: '왕의 씨족 코헤이'),
  LocalizedText(
      chs: '王之氏族·士官', jpn: '', eng: 'Royal Clan・Cygan', kor: '왕의 씨족 시간'),

  // category
  LocalizedText(chs: '门', jpn: '', eng: 'Door', kor: '문'),
  LocalizedText(chs: '手', jpn: '', eng: 'Hand/Arm', kor: '손'),
  LocalizedText(chs: '骷髅兵', jpn: '', eng: 'Skeleton', kor: '스켈레톤'),
  LocalizedText(chs: '龙牙兵', jpn: '', eng: 'Dragon Tooth Warrior', kor: '용아병'),
  LocalizedText(chs: '士兵', jpn: '', eng: 'Soldier', kor: '병사'),
  LocalizedText(chs: '僵尸', jpn: '', eng: 'Zombie', kor: '좀비'),
  LocalizedText(chs: '鬼魂', jpn: '', eng: 'Ghost', kor: '고스트'),
  LocalizedText(chs: '恶魔', jpn: '', eng: 'Demon', kor: '데몬'),
  LocalizedText(chs: '自动人偶', jpn: '', eng: 'Automata', kor: '오토마타'),
  LocalizedText(chs: '魔偶', jpn: '', eng: 'Golem', kor: '골렘'),
  LocalizedText(chs: '双足飞龙', jpn: '', eng: 'Wyvern', kor: '와이번'),
  LocalizedText(chs: '龙·巴修穆', jpn: '', eng: 'Dragon/Basmu', kor: '용/와이번'),
  LocalizedText(chs: '亚马逊人', jpn: '', eng: 'Amazoness', kor: '아마조네스'),
  LocalizedText(chs: '蛇女', jpn: '', eng: 'Lamia/Naga', kor: '뱀'),
  LocalizedText(chs: '半人马', jpn: '', eng: 'Centaur', kor: '켄타우로스'),
  LocalizedText(chs: '奇美拉', jpn: '', eng: 'Chimera', kor: '키메라'),
  LocalizedText(chs: '咒语书', jpn: '', eng: 'Book', kor: '책'),
  LocalizedText(chs: '人工生命体', jpn: '', eng: 'Homunculus', kor: '호문쿨루스'),
  LocalizedText(chs: '兽人', jpn: '', eng: 'Beastman', kor: '수인'),
  LocalizedText(chs: '混沌机械兵', jpn: '', eng: 'Helter Skelter', kor: '헬터 스켈터'),
  LocalizedText(chs: '尸人', jpn: '', eng: 'Deadman/Undead', kor: '시체'),
  // LocalizedText(chs: '七人御佐姬', jpn: '', eng: '', kor: ''),
  LocalizedText(chs: '巨大首领鬼魂', jpn: '', eng: 'Massive Ghost', kor: '휴즈 고스트'),
  LocalizedText(chs: '守护者', jpn: '', eng: 'Spriggan', kor: '스프리건'),
  LocalizedText(chs: '双角兽', jpn: '', eng: 'Bicorn', kor: '바이콘'),
  LocalizedText(chs: '凝视者', jpn: '', eng: 'Gazer', kor: '게이저'),
  LocalizedText(
      chs: '噬魂者·乌修穆迦尔', jpn: '', eng: 'Soul Eater/Usumgallu', kor: '소울이터/우슘갈루'),
  LocalizedText(
      chs: '机械化步兵', jpn: '', eng: 'Mechanized Infantry', kor: '기계화 보병'),
  LocalizedText(chs: '凯尔特士兵', jpn: '', eng: 'Celtic Soldier', kor: '켈트 병사'),
  LocalizedText(
      chs: '海魔·穆修玛夫', jpn: '', eng: 'Little Demon/Musmahhu', kor: '소마/무슈마후'),
  LocalizedText(chs: '翅刃虫', jpn: '', eng: 'Bladed-Wing Insect', kor: '시인충'),
  LocalizedText(chs: '哈桑', jpn: '', eng: 'Hassan', kor: '하산'),
  LocalizedText(
      chs: '醉酒城里人·农村亭卒', jpn: '', eng: 'Drunken Citizen', kor: '취한 교토 사람'),
  LocalizedText(chs: '日本鬼', jpn: '', eng: 'Japanese Oni', kor: '오니'),
  LocalizedText(chs: '失心之人', jpn: '', eng: 'Soulless One', kor: '마음을 잃은 자'),
  LocalizedText(chs: '肃正骑士', jpn: '', eng: 'Knight Enforcer', kor: '숙정기사'),
  LocalizedText(
      chs: '自动防卫装置', jpn: '', eng: 'Automated Defense', kor: '자동방위장치'),
  LocalizedText(chs: '斯芬克斯', jpn: '', eng: 'Sphinx', kor: '스핑크스'),
  LocalizedText(chs: '伊夫利塔', jpn: '', eng: 'Efreet', kor: '이프리트'),
  LocalizedText(chs: '寄居蟹', jpn: '', eng: 'Hermit Crab', kor: '소라게'),
  LocalizedText(chs: '魔猪', jpn: '', eng: 'Demon Boar', kor: '괴물 멧돼지'),
  LocalizedText(chs: '巨大魔猪', jpn: '', eng: 'Calydonian Boar', kor: '거대 괴물 멧돼지'),
  // LocalizedText(chs: '迷你小库', jpn: '', eng: '', kor: ''),
  // LocalizedText(chs: '魔法杖', jpn: '', eng: 'Magical Stick', kor: ''),
  LocalizedText(chs: '乌利迪姆·冰雪之狼', jpn: '', eng: 'Uridimmu-like', kor: '우리딤무'),
  LocalizedText(chs: '蝎狮·乌伽尔·冰雪加姆', jpn: '', eng: 'Ugallu-like', kor: '우갈루'),
  LocalizedText(chs: '巴西利斯克·穆修胡休', jpn: '', eng: 'Mushussu-like', kor: '무슈후슈'),
  // LocalizedText(chs: '复合神性戈耳工', jpn: '', eng: '', kor: ''),
  // LocalizedText(chs: '拉赫穆', jpn: '', eng: '', kor: ''),
  // LocalizedText(chs: '魔性之女', jpn: '', eng: '', kor: ''),
  LocalizedText(chs: '小混混·流氓', jpn: '', eng: 'Hoodlum/Yakuza', kor: '불량배'),
  LocalizedText(chs: '雀蜂', jpn: '', eng: 'Hornet', kor: '말벌'),
  LocalizedText(chs: '酷吏', jpn: '', eng: 'Atrocious Officer', kor: '혹리'),
  LocalizedText(chs: '女海盗', jpn: '', eng: 'Female Pirate', kor: '여해적'),
  LocalizedText(chs: '许德拉·大蛇', jpn: '', eng: 'Hydra', kor: '히드라'),
  // LocalizedText(chs: '古伽兰那', jpn: '', eng: '', kor: ''),
  LocalizedText(chs: '黑武者', jpn: '', eng: 'Black Samurai', kor: '검은 무사'),
  // LocalizedText(chs: '量产型机械伊丽亲', jpn: '', eng: '', kor: ''),
  LocalizedText(chs: '食尸鬼', jpn: '', eng: 'Ghoul', kor: '구울'),
  LocalizedText(chs: '灰狼', jpn: '', eng: 'Grey Wolf', kor: '회색 늑대'),
  LocalizedText(chs: '夏塔克鸟', jpn: '', eng: 'Shantak', kor: '산타크'),
  // LocalizedText(chs: '邪恶迦鲁拉灵', jpn: '', eng: '', kor: ''),
  LocalizedText(chs: '杀戮猎兵', jpn: '', eng: 'Oprichnik', kor: '살육엽병'),
  // LocalizedText(chs: '伊凡雷帝', jpn: '', eng: '', kor: ''),
  LocalizedText(chs: '空想树', jpn: '', eng: 'Tree of Emptiness', kor: '공상수'),
  LocalizedText(chs: '雅嘎', jpn: '', eng: 'Yaga', kor: '야가'),
  // LocalizedText(chs: '拟态天之杯', jpn: '', eng: '', kor: ''),
  // LocalizedText(chs: '英灵兵', jpn: '', eng: '', kor: ''),
  // LocalizedText(chs: '黑巨人', jpn: '', eng: '', kor: ''),
  LocalizedText(chs: '巨人', jpn: '', eng: 'Hrimthurse', kor: '서리 거인'),
  LocalizedText(chs: '瓦尔基里', jpn: '', eng: 'Walkure', kor: '발키리'),
  LocalizedText(chs: '斩首鸡', jpn: '', eng: 'Chicken', kor: '보팔 치킨'),
  LocalizedText(chs: '禁卫兵', jpn: '', eng: 'Royal Guard', kor: '근위병'),
  LocalizedText(
      chs: '多多益善号', jpn: '', eng: 'The More The Merrier', kor: '다다익선 호'),
  LocalizedText(chs: '鵺·秽神', jpn: '', eng: 'Nue', kor: '누에'),
  LocalizedText(chs: '魔猿', jpn: '', eng: 'Demonic Monkey', kor: '요괴 원숭이'),
  // LocalizedText(chs: '女官', jpn: '', eng: '', kor: ''),
  // LocalizedText(chs: '迦摩/魔罗', jpn: '', eng: '', kor: ''),
  // LocalizedText(chs: '谟涅摩叙涅', jpn: '', eng: '', kor: ''),
  // LocalizedText(chs: '庄严的石像', jpn: '', eng: '', kor: ''),
  LocalizedText(chs: '迦利', jpn: '', eng: 'Kali', kor: '칼리'),
  LocalizedText(chs: '伟大那伽', jpn: '', eng: 'Mahanaga', kor: '마하나가'),
  // LocalizedText(chs: '柴田胜家', jpn: '', eng: '', kor: ''),
  LocalizedText(chs: '亚特兰蒂斯防卫兵', jpn: '', eng: 'Atlantean', kor: '아틀란티스 방위병'),
  LocalizedText(chs: '刻耳柏洛斯', jpn: '', eng: 'Cerbernus', kor: '케르베로스'),
  LocalizedText(
      chs: '广域歼灭兵器',
      jpn: '',
      eng: 'Wide-Area Annihilation Ordnace',
      kor: '광역 섬멸 병기'),
  // LocalizedText(chs: '真体机神', jpn: '', eng: '', kor: ''),
  LocalizedText(
      chs: '奥林波斯士兵', jpn: '', eng: 'Olympian Soldier', kor: '올림포스 병사'),
  // LocalizedText(chs: '塔罗斯', jpn: '', eng: '', kor: ''),
  // LocalizedText(chs: '『玩赏之兽』', jpn: '', eng: '', kor: ''),
  // LocalizedText(chs: '帮佣人偶', jpn: '', eng: '', kor: ''),
  // LocalizedText(chs: '芹泽鸭', jpn: '', eng: '', kor: ''),
  // LocalizedText(chs: '不可视的敌意', jpn: '', eng: '', kor: ''),
  // LocalizedText(chs: '敌舰阿尔法', jpn: '', eng: '', kor: ''),
  LocalizedText(chs: '土蜘蛛', jpn: '', eng: 'Tsuchigumo', kor: '츠치구모'),
  // LocalizedText(chs: '罗刹王·髑髅乌帽子芦屋道满', jpn: '', eng: '', kor: ''),
  // LocalizedText(chs: '弗栗多之魔', jpn: '', eng: '', kor: ''),
  LocalizedText(chs: '蛇', jpn: '', eng: 'Bhujanga', kor: '부장가'),
  // LocalizedText(chs: '鸦天狗', jpn: '', eng: '', kor: ''),
  // LocalizedText(chs: '超宝宝卡莲', jpn: '', eng: '', kor: ''),
  LocalizedText(chs: '死神', jpn: '', eng: 'Mors', kor: '모스'),
  LocalizedText(chs: '摩根士兵', jpn: '', eng: 'Queen\'s Soldier', kor: '여왕의 병사'),
  // LocalizedText(chs: '灾厄', jpn: '', eng: '', kor: '재난'),
  // LocalizedText(chs: '亚铃百种', jpn: '', eng: '', kor: ''),
]);
