part of localized;

final _localizedMasterMission = LocalizedGroup([
  ..._localizedGender.values,
  ..._localizedSvtFilter.values,
  ...const [
    LocalizedText(chs: '从者', jpn: 'サーヴァント', eng: 'Servant', kor: '서번트'),
    LocalizedText(chs: '剑阶', jpn: 'セイバー', eng: 'Saber', kor: '세이버'),
    LocalizedText(chs: '弓阶', jpn: 'アーチャー', eng: 'Archer', kor: '아처'),
    LocalizedText(chs: '枪阶', jpn: 'ランサー', eng: 'Lancer', kor: '랜서'),
    LocalizedText(chs: '骑阶', jpn: 'ライダー', eng: 'Rider', kor: '라이더'),
    LocalizedText(chs: '术阶', jpn: 'チャスター', eng: 'Caster', kor: '캐스터'),
    LocalizedText(chs: '杀阶', jpn: 'アサシン', eng: 'Assassin', kor: '어새신'),
    LocalizedText(chs: '狂阶', jpn: 'バーサーカー', eng: 'Berserker', kor: '버서커'),
    LocalizedText(chs: '裁阶', jpn: 'ルーラー', eng: 'Ruler', kor: '룰러'),
    LocalizedText(chs: '仇阶', jpn: 'アヴェンジャー', eng: 'Avenger', kor: '어벤저'),

    LocalizedText(chs: '『天』之力', jpn: '『天』の力', eng: 'Attribute Sky', kor: '천'),
    LocalizedText(chs: '『地』之力', jpn: '『地』の力', eng: 'Attribute Earth', kor: '지'),
    LocalizedText(chs: '『人』之力', jpn: '『人』の力', eng: 'Attribute Man', kor: '인'),
    LocalizedText(chs: '『星』之力', jpn: '『星』の力', eng: 'Attribute Star', kor: '별'),
    // Localized(chs: '女性', jpn: '', eng: 'Female', kor: '여성'),
    // Localized(chs: '男性', jpn: '', eng: 'Male', kor: '남성'),
    // Localized(chs: '其他性别', jpn: '', eng: '', kor: '성별 없음'),
    LocalizedText(
        chs: '『秩序』属性', jpn: '', eng: 'Alignment Lawful', kor: '『질서』속성'),
    LocalizedText(
        chs: '『混沌』属性', jpn: '', eng: 'Alignment Chaotic', kor: '『혼돈』속성'),
    LocalizedText(
        chs: '『中立』属性', jpn: '', eng: 'Alignment Neutral', kor: '『중립』속성'),
    LocalizedText(chs: '『善』属性', jpn: '', eng: 'Alignment Good', kor: '『선』속성'),
    LocalizedText(chs: '『恶』属性', jpn: '', eng: 'Alignment Evil', kor: '『악』속성'),
    LocalizedText(
        chs: '『中庸』属性', jpn: '', eng: 'Alignment Balanced', kor: '『중용』속성'),
    LocalizedText(chs: '『狂』属性', jpn: '', eng: 'Alignment Mad', kor: '『광』속성'),

    // LocalizedText(chs: '龙', jpn: '竜', eng: 'Dragon', kor: '용'),
    // LocalizedText(chs: '骑乘', jpn: '', eng: '', kor: '기승'),
    // LocalizedText(chs: '神性', jpn: '神性', eng: 'Divine', kor: '신성'),
    // LocalizedText(chs: '猛兽', jpn: '猛獸', eng: 'Beast', kor: '맹수'),
    // LocalizedText(chs: '王', jpn: '王', eng: 'King', kor: '왕'),
    // LocalizedText(chs: '罗马', jpn: '', eng: '', kor: '로마'),
    // LocalizedText(chs: '呆毛脸', jpn: '', eng: '', kor: '알트리아 얼굴'),
    // LocalizedText(chs: '所爱之人', jpn: '', eng: '', kor: '사랑하는 자'),
    // LocalizedText(chs: '希腊神话系男性', jpn: '', eng: '', kor: '그리스 신화계 남성'),
    // LocalizedText(chs: '阿耳戈船相关人员', jpn: '', eng: '', kor: '아르고호 관계자'),
    // LocalizedText(chs: '魔性', jpn: '魔性', eng: 'Demonic', kor: '악마'),
    // LocalizedText(chs: '天地从者', jpn: '', eng: '', kor: ''),
    // LocalizedText(chs: '人型', jpn: '人型', eng: 'Humanoid', kor: '인간형'),

    LocalizedText(chs: '人类', jpn: '', eng: 'Human', kor: '인간'),
    LocalizedText(chs: '和风', jpn: '和風', eng: 'Japanese', kor: '일본'),
    LocalizedText(chs: '太阳', jpn: '', eng: 'Sun', kor: '태양'),
    LocalizedText(chs: '幸运A+以上', jpn: '幸運A+', eng: 'Lucky A+', kor: '행운 A+'),
    LocalizedText(chs: '哈桑系', jpn: '', eng: 'Hassan', kor: '하산'),
    // LocalizedText(chs: '犬型', jpn: '', eng: '', kor: '견형'),
    // LocalizedMessage(chs: '阿斯克勒庇俄斯', jpn: '', eng: '', kor: '아스클레피오스'),
    // LocalizedMessage(chs: '马嘶', jpn: '', eng: '', kor: '아슈바타만'),

    // enemy traits
    LocalizedText(chs: '小怪', jpn: 'エネミー', eng: 'Enemy', kor: '적'),

    // LocalizedMessage(chs: '女性', jpn: '', eng: '', kor: '여성'),
    // LocalizedMessage(chs: '男性', jpn: '', eng: '', kor: '남성'),
    // LocalizedMessage(chs: '王', jpn: '', eng: '', kor: '왕'),
    // LocalizedMessage(chs: '魔性', jpn: '', eng: '', kor: '마성'),
    // LocalizedMessage(chs: '人型', jpn: '', eng: '', kor: '인간형'),
    // LocalizedMessage(chs: '人类', jpn: '', eng: '', kor: '인간'),
    // LocalizedMessage(chs: '神性', jpn: '', eng: '', kor: '신성'),
    // LocalizedMessage(chs: '希腊神话系男性', jpn: '', eng: '', kor: '그리스신화계남성'),
    // LocalizedMessage(chs: '猛兽', jpn: '', eng: '', kor: '맹수'),
    // LocalizedMessage(chs: '『恶』属性', jpn: '', eng: '', kor: '『악』속성'),
    // Localized(chs: '龙', jpn: '', eng: '', kor: '용'),

    LocalizedText(chs: '死灵', jpn: '', eng: 'Undead', kor: '사령'),
    LocalizedText(chs: '犬型', jpn: '', eng: 'Dog', kor: '개'),
    LocalizedText(chs: '罗马', jpn: '', eng: 'Roman', kor: '로마'),
    LocalizedText(chs: '恶魔', jpn: '悪魔', eng: 'Demon', kor: '악마'),
    LocalizedText(chs: '超巨大', jpn: '超巨大', eng: 'Super Large', kor: '초거대'),

    LocalizedText(chs: '门系', jpn: '', eng: 'Door', kor: '문'),
    LocalizedText(chs: '骷髅系', jpn: '', eng: 'Skeleton', kor: '스켈레톤'),
    LocalizedText(chs: '士兵系', jpn: '', eng: 'Soldier', kor: '프랑스 병사'),
    LocalizedText(chs: '双足飞龙系', jpn: '', eng: 'Wyvern', kor: '와이번'),
    LocalizedText(chs: '僵尸系', jpn: '', eng: 'Zombie', kor: '좀비'),
    LocalizedText(chs: '兽人系', jpn: '', eng: 'Were-Animals', kor: '수인'),
    LocalizedText(chs: '魔偶系', jpn: '', eng: 'Golem', kor: '골렘'),
    LocalizedText(chs: '鬼魂系', jpn: '', eng: 'Ghost', kor: '고스트'),
    LocalizedText(chs: '奇美拉系', jpn: '', eng: 'Chimera', kor: '키메라'),
    LocalizedText(chs: '寄居蟹系', jpn: '', eng: 'Hermit Crab', kor: '소라게'),
    LocalizedText(chs: '蛇女系', jpn: '', eng: 'Lamia', kor: '라미아'),
    LocalizedText(chs: '半人马系', jpn: '', eng: 'Centaur', kor: '켄타우르스'),
    LocalizedText(chs: '亚马逊系', jpn: '', eng: 'Amazoness', kor: '아마조네스'),
    LocalizedText(chs: '自动人偶系', jpn: '', eng: 'Automata', kor: '오토마타'),
    LocalizedText(chs: '人工生命体系', jpn: '', eng: 'Homunculus', kor: '호문클루스'),
    LocalizedText(chs: '书页系', jpn: '', eng: 'Book', kor: '책'),
    LocalizedText(chs: '混沌机械兵系', jpn: '', eng: 'Helter Skelter', kor: '헬터 스켈터'),
    LocalizedText(
        chs: '机械化步兵系', jpn: '', eng: 'Mechanized Infantry', kor: '기계화보병'),
    LocalizedText(chs: '凯尔特士兵系', jpn: '', eng: 'Celtic Soldier', kor: '켈트병사'),
    LocalizedText(chs: '噬魂者系', jpn: '', eng: 'Soul Easter', kor: '소울이터'),
    LocalizedText(chs: '凝视者系', jpn: '', eng: 'Gazer', kor: '게이저'),
    LocalizedText(chs: '双角兽系', jpn: '', eng: 'Bicorn', kor: '비콘'),
    LocalizedText(chs: '守护者系', jpn: '', eng: 'Spriggan', kor: '스프리건'),
    LocalizedText(chs: '斯芬克斯系', jpn: '', eng: 'Sphinx', kor: '스핑크스'),
    LocalizedText(chs: '伊夫利塔系', jpn: '', eng: 'Efreet', kor: '이프리트'),
    LocalizedText(chs: '失心者系', jpn: '', eng: 'Soulless One', kor: '마음을 잃은 자'),
    LocalizedText(chs: '骑士系', jpn: '', eng: 'Knight', kor: '기사'),
    LocalizedText(
        chs: '自动防卫装置系', jpn: '', eng: 'Automated Defense Unit', kor: '자동방위장치'),
    LocalizedText(chs: '乌利迪姆系', jpn: '', eng: 'Uridimmu', kor: '우리딤무'),
    LocalizedText(chs: '乌伽尔系', jpn: '', eng: 'Ugallu', kor: '우갈루'),
    LocalizedText(chs: '穆修胡休系', jpn: '', eng: 'Mušḫuššu', kor: '무슈후슈'),
    LocalizedText(chs: '海魔系', jpn: '', eng: 'Sea Demon', kor: '해마'),
    LocalizedText(chs: '巨龙系', jpn: '', eng: 'Great Dragon', kor: '그레이트 드래곤'),
    LocalizedText(chs: '魔猪系', jpn: '', eng: 'Demon Boar', kor: '마저'),
    LocalizedText(chs: '巨大魔猪系', jpn: '', eng: 'Calydonian Boar', kor: '거대 마저'),
    LocalizedText(chs: '小混混系', jpn: '', eng: 'Hoodlum', kor: '불량배'),
    LocalizedText(chs: '雀蜂系', jpn: '', eng: 'Hornet', kor: '말벌'),
    LocalizedText(chs: '流氓系', jpn: '', eng: 'Yakuza', kor: '야쿠자'),
    LocalizedText(chs: '恶魔系', jpn: '', eng: 'Daemon', kor: '데몬'),
    LocalizedText(chs: '女海盗系', jpn: '', eng: 'Female Pirate', kor: '여자 해적'),
    LocalizedText(chs: '酷吏系', jpn: '', eng: 'Atrocious Officer', kor: '혹리'),
    LocalizedText(chs: '许德拉系', jpn: '', eng: 'Hydra', kor: '히드라'),
    LocalizedText(chs: '黑武者系', jpn: '', eng: 'Black Samurai', kor: '검은 무사'),
    LocalizedText(chs: '祟鬼系', jpn: '', eng: 'Cursed Oni', kor: '수귀'),
    LocalizedText(chs: '秽神系', jpn: '', eng: 'Corrupted God', kor: '부정한 신'),
    LocalizedText(chs: '灰狼系', jpn: '', eng: 'Grey Wolf', kor: '회색 늑대'),
    LocalizedText(chs: '食尸鬼系', jpn: '', eng: 'Ghoul', kor: '구울'),
    LocalizedText(chs: '夏塔克鸟系', jpn: '', eng: 'Shantak', kor: '샨타크'),
    LocalizedText(chs: '雅嘎系', jpn: '', eng: 'Yaga', kor: '야가'),
    LocalizedText(chs: '杀戮猎兵系', jpn: '', eng: 'Oprichnik', kor: '살육엽병'),
    LocalizedText(chs: '巨人系', jpn: '', eng: 'Jötunn', kor: '서리 거인'),
    LocalizedText(chs: '瓦尔基里系', jpn: '', eng: 'Walküre', kor: '발키리'),
    LocalizedText(chs: '坦克系', jpn: '', eng: 'Tank', kor: '전차'),
    LocalizedText(chs: '禁卫兵系', jpn: '', eng: 'Royal Guard', kor: '근위병'),
    LocalizedText(chs: '迦利系', jpn: '', eng: 'Kali', kor: '칼리'),
    LocalizedText(chs: '亡者系', jpn: '', eng: 'Deceased One', kor: '망자'),
    LocalizedText(chs: '伟大那伽系', jpn: '', eng: 'Mahānaga', kor: '마하 나가'),
    LocalizedText(chs: '刻耳柏洛斯系', jpn: '', eng: 'Cerberus', kor: '케르베로스'),
    LocalizedText(
        chs: '亚特兰蒂斯防卫兵系',
        jpn: '',
        eng: 'Atlantean Defense Troop',
        kor: '아틀란티스의 수비병'),
    LocalizedText(
        chs: '广域歼灭兵器系',
        jpn: '',
        eng: 'Wide-Area Annihilation Ordnance',
        kor: '광역 섬멸 병기'),
    LocalizedText(
        chs: '奥林波斯兵系', jpn: '', eng: 'Olympian Soldier', kor: '올림포스 병사'),
    LocalizedText(chs: '咒语书系', jpn: '', eng: 'Spell Book'),
    LocalizedText(chs: '土蜘蛛系', jpn: '', eng: 'Tsuchigumo'),
    LocalizedText(chs: '大翁鬼系', jpn: '', eng: 'Hakushikijyo'),
    LocalizedText(chs: '小鬼系', jpn: '', eng: 'Oni Imp'),
    LocalizedText(chs: '龙牙兵系', jpn: '', eng: 'Dragon Tooth Warrior'),

    // fields
    LocalizedText(chs: '场地', jpn: 'フィールド', eng: 'Field', kor: '필드'),
    LocalizedText(chs: '燃烧', jpn: '炎上', eng: 'Flaming', kor: '염상'),
    LocalizedText(chs: '都市', jpn: '都市', eng: 'City', kor: '도시'),
    LocalizedText(
        chs: '城市', jpn: '街', eng: 'Street', kor: '거리'), // not verified
    LocalizedText(
        chs: '地下', jpn: '地下', eng: 'Underground', kor: '지하'), // not verified
    LocalizedText(chs: '阳光', jpn: '陽射し', eng: 'Sunlight', kor: '햇빛'),
    LocalizedText(chs: '山丘', jpn: '丘', eng: 'Hill', kor: '언덕'),
    LocalizedText(chs: '森林', jpn: '森', eng: 'Forest', kor: '숲'),
    LocalizedText(chs: '城池', jpn: '城', eng: 'Castle', kor: '성'),
    LocalizedText(chs: '荒野', jpn: '荒野', eng: 'Wilderness', kor: '황야'),
    LocalizedText(
        chs: '山', jpn: '山', eng: 'Mountain', kor: '산'), // not verified
    LocalizedText(chs: '水边', jpn: '水辺', eng: 'Waterside', kor: '물가'),
    LocalizedText(
        chs: '沙滩·沙漠', jpn: '砂浜・砂漠', eng: 'Beach/Desert', kor: '모래사장・사막'),
    LocalizedText(chs: '神殿', jpn: '神殿', eng: 'Shrine', kor: '신전'),
    LocalizedText(chs: '岩山', jpn: '岩山', eng: 'Rocky Mountain', kor: '바위산'),
    LocalizedText(chs: '草原', jpn: '草原', eng: 'Prairie', kor: '초원'),
  ],
]);
