part of localized;

final _localizedMasterMission = LocalizedGroup([
  Localized(chs: '从者', jpn: 'サーヴァント', eng: 'Servant'),
  Localized(chs: '剑阶', jpn: 'セイバー', eng: 'Saber'),
  Localized(chs: '弓阶', jpn: 'アーチャー', eng: 'Archer'),
  Localized(chs: '枪阶', jpn: 'ランサー', eng: 'Lancer'),
  Localized(chs: '骑阶', jpn: 'ライダー', eng: 'Rider'),
  Localized(chs: '术阶', jpn: 'チャスター', eng: 'Caster'),
  Localized(chs: '杀阶', jpn: 'アサシン', eng: 'Assassin'),
  Localized(chs: '狂阶', jpn: 'バーサーカー', eng: 'Berserker'),
  Localized(chs: '裁阶', jpn: 'ルーラー', eng: 'Ruler'),
  Localized(chs: '仇阶', jpn: 'アヴェンジャー', eng: 'Avenger'),

  Localized(chs: '『天』之力', jpn: '『天』の力', eng: 'Sky Attribute'),
  Localized(chs: '『地』之力', jpn: '『地』の力', eng: 'Earth Attribute'),
  Localized(chs: '『人』之力', jpn: '『人』の力', eng: 'Man Attribute'),
  Localized(chs: '『星』之力', jpn: '『星』の力', eng: 'Star Attribute'),
  ..._localizedGender.values,
  // Localized(chs: '女性', jpn: '', eng: 'Female'),
  // Localized(chs: '男性', jpn: '', eng: 'Male'),
  // Localized(chs: '其他性别', jpn: '', eng: ''),
  Localized(chs: '『混沌』属性', jpn: '', eng: ''),
  Localized(chs: '『秩序』属性', jpn: '', eng: ''),
  Localized(chs: '『中立』属性', jpn: '', eng: ''),
  Localized(chs: '『善』属性', jpn: '', eng: ''),
  Localized(chs: '『恶』属性', jpn: '', eng: ''),
  Localized(chs: '『中庸』属性', jpn: '', eng: ''),
  Localized(chs: '『狂』属性', jpn: '', eng: ''),

  Localized(chs: '龙', jpn: '竜', eng: 'Dragon'),
  Localized(chs: '骑乘', jpn: '', eng: ''),
  Localized(chs: '神性', jpn: '神性', eng: 'Divine'),
  Localized(chs: '猛兽', jpn: '猛獸', eng: 'Beast'),
  Localized(chs: '王', jpn: '王', eng: 'King'),
  Localized(chs: '罗马', jpn: '', eng: ''),
  Localized(chs: '呆毛脸', jpn: '', eng: ''),
  Localized(chs: '所爱之人', jpn: '', eng: ''),
  Localized(chs: '希腊神话系男性', jpn: '', eng: ''),
  Localized(chs: '希腊神话男性', jpn: '', eng: ''),
  Localized(chs: '阿耳戈船相关人员', jpn: '', eng: ''),
  Localized(chs: '魔性', jpn: '魔性', eng: 'Demonic'),
  Localized(chs: '天地从者', jpn: '', eng: ''),
  Localized(chs: '人型', jpn: '人型', eng: 'Humanoid'),
  Localized(chs: '人类', jpn: '', eng: ''),
  Localized(chs: '和风', jpn: '', eng: ''),
  Localized(chs: '太阳', jpn: '', eng: ''),
  Localized(chs: '幸运A+以上', jpn: '', eng: ''),
  Localized(chs: '哈桑系', jpn: '', eng: 'Hassan'),
  Localized(chs: '犬型', jpn: '', eng: ''),
  // LocalizedMessage(chs: '阿斯克勒庇俄斯', jpn: '', eng: ''),
  // LocalizedMessage(chs: '马嘶', jpn: '', eng: ''),

  // enemy traits
  Localized(chs: '小怪', jpn: 'エネミー', eng: 'Enemy'),

  // LocalizedMessage(chs: '女性', jpn: '', eng: ''),
  // LocalizedMessage(chs: '男性', jpn: '', eng: ''),
  // LocalizedMessage(chs: '王', jpn: '', eng: ''),
  // LocalizedMessage(chs: '魔性', jpn: '', eng: ''),
  // LocalizedMessage(chs: '人型', jpn: '', eng: ''),
  // LocalizedMessage(chs: '人类', jpn: '', eng: ''),
  // LocalizedMessage(chs: '神性', jpn: '', eng: ''),
  // LocalizedMessage(chs: '希腊神话系男性', jpn: '', eng: ''),
  // LocalizedMessage(chs: '猛兽', jpn: '', eng: ''),
  // LocalizedMessage(chs: '『恶』属性', jpn: '', eng: ''),
  // Localized(chs: '龙', jpn: '', eng: ''),

  Localized(chs: '死灵', jpn: '', eng: 'Undead'),
  Localized(chs: '犬型', jpn: '', eng: ''),
  Localized(chs: '罗马', jpn: '', eng: 'Roman'),
  Localized(chs: '恶魔', jpn: '悪魔', eng: 'Demon'),
  Localized(chs: '超巨大', jpn: '超巨大', eng: 'Super Large'),

  Localized(chs: '门系', jpn: '', eng: 'Doors'),
  Localized(chs: '骷髅系', jpn: '', eng: ''),
  Localized(chs: '士兵系', jpn: '', eng: ''),
  Localized(chs: '双足飞龙系', jpn: '', eng: ''),
  Localized(chs: '僵尸系', jpn: '', eng: ''),
  Localized(chs: '兽人系', jpn: '', eng: ''),
  Localized(chs: '魔偶系', jpn: '', eng: ''),
  Localized(chs: '鬼魂系', jpn: '', eng: ''),
  Localized(chs: '奇美拉系', jpn: '', eng: ''),
  Localized(chs: '寄居蟹系', jpn: '', eng: ''),
  Localized(chs: '蛇女系', jpn: '', eng: ''),
  Localized(chs: '半人马系', jpn: '', eng: ''),
  Localized(chs: '亚马逊系', jpn: '', eng: 'Amazoness'),
  Localized(chs: '自动人偶系', jpn: '', eng: ''),
  Localized(chs: '人工生命体', jpn: '', eng: ''),
  Localized(chs: '人工生命体系', jpn: '', eng: ''),
  Localized(chs: '书页系', jpn: '', eng: ''),
  Localized(chs: '混沌机械兵系', jpn: '', eng: ''),
  Localized(chs: '机械化步兵系', jpn: '', eng: ''),
  Localized(chs: '凯尔特士兵系', jpn: '', eng: 'Celtic'),
  Localized(chs: '噬魂者系', jpn: '', eng: ''),
  Localized(chs: '凝视者系', jpn: '', eng: ''),
  Localized(chs: '双角兽系', jpn: '', eng: ''),
  Localized(chs: '守护者系', jpn: '', eng: ''),
  Localized(chs: '斯芬克斯系', jpn: '', eng: ''),
  Localized(chs: '伊夫利塔系', jpn: '', eng: 'Efreet'),
  Localized(chs: '失心者系', jpn: '', eng: 'Astrayed Ones'),
  Localized(chs: '骑士系', jpn: '', eng: 'Knight'),
  Localized(chs: '自动防卫装置系', jpn: '', eng: ''),
  Localized(chs: '乌利迪姆系', jpn: '', eng: ''),
  Localized(chs: '乌伽尔系', jpn: '', eng: ''),
  Localized(chs: '穆修胡休系', jpn: '', eng: ''),
  Localized(chs: '海魔系', jpn: '', eng: ''),
  Localized(chs: '穆修胡休', jpn: '', eng: ''),
  Localized(chs: '乌伽尔', jpn: '', eng: ''),
  Localized(chs: '巨龙系', jpn: '', eng: ''),
  Localized(chs: '魔猪系', jpn: '', eng: ''),
  Localized(chs: '巨大魔猪系', jpn: '', eng: ''),
  Localized(chs: '乌利迪姆', jpn: '', eng: ''),
  Localized(chs: '小混混系', jpn: '', eng: ''),
  Localized(chs: '雀蜂系', jpn: '', eng: 'Hornet'),
  Localized(chs: '流氓系', jpn: '', eng: ''),
  Localized(chs: '恶魔系', jpn: '', eng: ''),
  Localized(chs: '飞龙系', jpn: '', eng: ''),
  Localized(chs: '女海盗系', jpn: '', eng: ''),
  Localized(chs: '酷吏系', jpn: '', eng: ''),
  Localized(chs: '许德拉系', jpn: '', eng: ''),
  Localized(chs: '亚马逊人系', jpn: '', eng: ''),
  Localized(chs: '黑武者系', jpn: '', eng: ''),
  Localized(chs: '祟鬼系', jpn: '', eng: ''),
  Localized(chs: '秽神系', jpn: '', eng: ''),
  Localized(chs: '灰狼系', jpn: '', eng: ''),
  Localized(chs: '食尸鬼系', jpn: '', eng: ''),
  Localized(chs: '夏塔克鸟系', jpn: '', eng: ''),
  Localized(chs: '雅嘎系', jpn: '', eng: ''),
  Localized(chs: '杀戮猎兵系', jpn: '', eng: ''),
  Localized(chs: '巨人系', jpn: '', eng: ''),
  Localized(chs: '瓦尔基里系', jpn: '', eng: ''),
  Localized(chs: '坦克系', jpn: '', eng: ''),
  Localized(chs: '禁卫兵系', jpn: '', eng: ''),
  Localized(chs: '迦利系', jpn: '', eng: ''),
  Localized(chs: '亡者系', jpn: '', eng: ''),
  Localized(chs: '伟大那伽系', jpn: '', eng: ''),
  Localized(chs: '刻耳柏洛斯系', jpn: '', eng: ''),
  Localized(chs: '亚特兰蒂斯防卫兵系', jpn: '', eng: ''),
  Localized(chs: '广域歼灭兵器系', jpn: '', eng: ''),
  Localized(chs: '奥林波斯兵系', jpn: '', eng: ''),

  // fields
  Localized(chs: '燃烧', jpn: '炎上', eng: 'Flaming'),
  Localized(chs: '都市', jpn: '都市', eng: 'City'),
  Localized(chs: '城市', jpn: '', eng: ''),
  Localized(chs: '地下', jpn: '', eng: ''),
  Localized(chs: '阳光', jpn: '陽射し', eng: 'Sunlight'),
  Localized(chs: '山丘', jpn: '丘', eng: 'Hill'),
  Localized(chs: '森林', jpn: '森', eng: 'Forest'),
  Localized(chs: '城池', jpn: '城', eng: 'Castle'),
  Localized(chs: '荒野', jpn: '荒野', eng: 'Wilderness'),
  Localized(chs: '山', jpn: '', eng: ''),
  Localized(chs: '水边', jpn: '水辺', eng: 'Waterside'),
  Localized(chs: '沙滩·沙漠', jpn: '砂浜・砂漠', eng: 'Beach/Desert'),
  Localized(chs: '神殿', jpn: '神殿', eng: 'Shrine'),
  Localized(chs: '岩山', jpn: '岩山', eng: 'Rocky Mountain'),
  Localized(chs: '草原', jpn: '草原', eng: 'Prairie'),
]);
