targets:
  $default:
    sources:
      include:
        - $package$
        - lib/$lib$
        - pubspec.*

  gamedata:
    sources:
      include:
        - lib/models/gamedata/**
    builders:
      source_gen|combining_builder:
        options:
          build_extensions:
            'lib/models/{{0}}/{{1}}.dart': 'lib/generated/models/{{0}}/{{1}}.g.dart'
      json_serializable:
        options:
          any_map: true
          checked: false
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: true
          field_rename: none
          generic_argument_factories: true
          ignore_unannotated: false
          include_if_null: true

  userdata:
    sources:
      include:
        - lib/models/api/**
        - lib/models/userdata/**
        - lib/models/shared/**
    builders:
      source_gen|combining_builder:
        options:
          build_extensions:
            'lib/models/{{0}}/{{1}}.dart': 'lib/generated/models/{{0}}/{{1}}.g.dart'
      json_serializable:
        options:
          any_map: true
          checked: true
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: true
          field_rename: none
          generic_argument_factories: true
          ignore_unannotated: false
          include_if_null: true
